/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import Australia from './src/plugins/countries/Australia/names';
import Austria from './src/plugins/countries/Austria/names';
import Belgium from './src/plugins/countries/Belgium/names';
import Brazil from './src/plugins/countries/Brazil/names';
import Canada from './src/plugins/countries/Canada/names';
import Nigeria from './src/plugins/countries/Nigeria/names';
import US from './src/plugins/countries/US/names';

const nameFiles = {
	Australia,
	Austria,
	Belgium,
	Brazil,
	Canada,
	Nigeria,
	US
};
export default nameFiles;

export type CountryNameFiles = keyof typeof nameFiles;
