/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import Australia from './src/plugins/countries/Australia/names';
import Austria from './src/plugins/countries/Austria/names';
import Belgium from './src/plugins/countries/Belgium/names';
import Brazil from './src/plugins/countries/Brazil/names';
import Canada from './src/plugins/countries/Canada/names';
import Chile from './src/plugins/countries/Chile/names';
import China from './src/plugins/countries/China/names';
import Germany from './src/plugins/countries/Germany/names';
import India from './src/plugins/countries/India/names';
import Nigeria from './src/plugins/countries/Nigeria/names';
import Spain from './src/plugins/countries/Spain/names';
import US from './src/plugins/countries/US/names';
import Vietnam from './src/plugins/countries/Vietnam/names';

const nameFiles = {
	Australia,
	Austria,
	Belgium,
	Brazil,
	Canada,
	Chile,
	China,
	Germany,
	India,
	Nigeria,
	Spain,
	US,
	Vietnam
};
export default nameFiles;

export type CountryNameFiles = keyof typeof nameFiles;
