/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import Alphanumeric from './src/plugins/dataTypes/Alphanumeric/config';
import AutoIncrement from './src/plugins/dataTypes/AutoIncrement/config';
import BitcoinAddress from './src/plugins/dataTypes/BitcoinAddress/config';
import Boolean from './src/plugins/dataTypes/Boolean/config';
import CVV from './src/plugins/dataTypes/CVV/config';
import City from './src/plugins/dataTypes/City/config';
import Colour from './src/plugins/dataTypes/Colour/config';
import Company from './src/plugins/dataTypes/Company/config';
import Computed from './src/plugins/dataTypes/Computed/config';
import Constant from './src/plugins/dataTypes/Constant/config';
import Country from './src/plugins/dataTypes/Country/config';
import Currency from './src/plugins/dataTypes/Currency/config';
import Date from './src/plugins/dataTypes/Date/config';
import Email from './src/plugins/dataTypes/Email/config';
import GUID from './src/plugins/dataTypes/GUID/config';
import IBAN from './src/plugins/dataTypes/IBAN/config';
import LatLng from './src/plugins/dataTypes/LatLng/config';
import List from './src/plugins/dataTypes/List/config';
import Names from './src/plugins/dataTypes/Names/config';
import NormalDistribution from './src/plugins/dataTypes/NormalDistribution/config';
import NumberRange from './src/plugins/dataTypes/NumberRange/config';
import OrganizationNumber from './src/plugins/dataTypes/OrganizationNumber/config';
import PAN from './src/plugins/dataTypes/PAN/config';
import PIN from './src/plugins/dataTypes/PIN/config';
import PersonalNumber from './src/plugins/dataTypes/PersonalNumber/config';
import Phone from './src/plugins/dataTypes/Phone/config';
import PostalZip from './src/plugins/dataTypes/PostalZip/config';
import Region from './src/plugins/dataTypes/Region/config';
import Rut from './src/plugins/dataTypes/Rut/config';
import SIRET from './src/plugins/dataTypes/SIRET/config';
import StreetAddress from './src/plugins/dataTypes/StreetAddress/config';
import TextFixed from './src/plugins/dataTypes/TextFixed/config';
import TextRandom from './src/plugins/dataTypes/TextRandom/config';
import Time from './src/plugins/dataTypes/Time/config';
import Track1 from './src/plugins/dataTypes/Track1/config';
import Track2 from './src/plugins/dataTypes/Track2/config';
import URLs from './src/plugins/dataTypes/URLs/config';
import WeightedList from './src/plugins/dataTypes/WeightedList/config';

export const dataTypes = {
	Alphanumeric,
	AutoIncrement,
	BitcoinAddress,
	Boolean,
	CVV,
	City,
	Colour,
	Company,
	Computed,
	Constant,
	Country,
	Currency,
	Date,
	Email,
	GUID,
	IBAN,
	LatLng,
	List,
	Names,
	NormalDistribution,
	NumberRange,
	OrganizationNumber,
	PAN,
	PIN,
	PersonalNumber,
	Phone,
	PostalZip,
	Region,
	Rut,
	SIRET,
	StreetAddress,
	TextFixed,
	TextRandom,
	Time,
	Track1,
	Track2,
	URLs,
	WeightedList
};

export type DataTypeFolder = keyof typeof dataTypes;

export const blacklistedDataTypeFolders = ['BitcoinAddress','OrganizationNumber','PersonalNumber','SIRET'];

import CSV from './src/plugins/exportTypes/CSV/config';
import CSharp from './src/plugins/exportTypes/CSharp/config';
import HTML from './src/plugins/exportTypes/HTML/config';
import JSON from './src/plugins/exportTypes/JSON/config';
import Javascript from './src/plugins/exportTypes/Javascript/config';
import LDIF from './src/plugins/exportTypes/LDIF/config';
import PHP from './src/plugins/exportTypes/PHP/config';
import Perl from './src/plugins/exportTypes/Perl/config';
import Python from './src/plugins/exportTypes/Python/config';
import Ruby from './src/plugins/exportTypes/Ruby/config';
import SQL from './src/plugins/exportTypes/SQL/config';
import Typescript from './src/plugins/exportTypes/Typescript/config';
import XML from './src/plugins/exportTypes/XML/config';

export const exportTypes = {
	CSV,
	CSharp,
	HTML,
	JSON,
	Javascript,
	LDIF,
	PHP,
	Perl,
	Python,
	Ruby,
	SQL,
	Typescript,
	XML
};

export type ExportTypeFolder = keyof typeof exportTypes;

import CountryAustralia from './src/plugins/countries/Australia/bundle';
import CountryAustria from './src/plugins/countries/Austria/bundle';
import CountryBelgium from './src/plugins/countries/Belgium/bundle';
import CountryBrazil from './src/plugins/countries/Brazil/bundle';
import CountryCanada from './src/plugins/countries/Canada/bundle';
import CountryChile from './src/plugins/countries/Chile/bundle';
import CountryChina from './src/plugins/countries/China/bundle';
import CountryColombia from './src/plugins/countries/Colombia/bundle';
import CountryCostaRica from './src/plugins/countries/CostaRica/bundle';
import CountryFrance from './src/plugins/countries/France/bundle';
import CountryGermany from './src/plugins/countries/Germany/bundle';
import CountryIndia from './src/plugins/countries/India/bundle';
import CountryIndonesia from './src/plugins/countries/Indonesia/bundle';
import CountryIreland from './src/plugins/countries/Ireland/bundle';
import CountryItaly from './src/plugins/countries/Italy/bundle';
import CountryMexico from './src/plugins/countries/Mexico/bundle';
import CountryNetherlands from './src/plugins/countries/Netherlands/bundle';
import CountryNewZealand from './src/plugins/countries/NewZealand/bundle';
import CountryNigeria from './src/plugins/countries/Nigeria/bundle';
import CountryNorway from './src/plugins/countries/Norway/bundle';
import CountryPakistan from './src/plugins/countries/Pakistan/bundle';
import CountryPeru from './src/plugins/countries/Peru/bundle';
import CountryPhilippines from './src/plugins/countries/Philippines/bundle';
import CountryPoland from './src/plugins/countries/Poland/bundle';
import CountryRussia from './src/plugins/countries/Russia/bundle';
import CountrySingapore from './src/plugins/countries/Singapore/bundle';
import CountrySouthAfrica from './src/plugins/countries/SouthAfrica/bundle';
import CountrySouthKorea from './src/plugins/countries/SouthKorea/bundle';
import CountrySpain from './src/plugins/countries/Spain/bundle';
import CountrySweden from './src/plugins/countries/Sweden/bundle';
import CountryTurkey from './src/plugins/countries/Turkey/bundle';
import CountryUK from './src/plugins/countries/UK/bundle';
import CountryUS from './src/plugins/countries/US/bundle';
import CountryUkraine from './src/plugins/countries/Ukraine/bundle';
import CountryVietnam from './src/plugins/countries/Vietnam/bundle';

export const countryList = ['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'CostaRica', 'France', 'Germany', 'India', 'Indonesia', 'Ireland', 'Italy', 'Mexico', 'Netherlands', 'NewZealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines', 'Poland', 'Russia', 'Singapore', 'SouthAfrica', 'SouthKorea', 'Spain', 'Sweden', 'Turkey', 'UK', 'US', 'Ukraine', 'Vietnam'];
export const countries = ['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'CostaRica', 'France', 'Germany', 'India', 'Indonesia', 'Ireland', 'Italy', 'Mexico', 'Netherlands', 'NewZealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines', 'Poland', 'Russia', 'Singapore', 'SouthAfrica', 'SouthKorea', 'Spain', 'Sweden', 'Turkey', 'UK', 'US', 'Ukraine', 'Vietnam'] as const;
export const countryMethods = {
	Australia: CountryAustralia,
	Austria: CountryAustria,
	Belgium: CountryBelgium,
	Brazil: CountryBrazil,
	Canada: CountryCanada,
	Chile: CountryChile,
	China: CountryChina,
	Colombia: CountryColombia,
	CostaRica: CountryCostaRica,
	France: CountryFrance,
	Germany: CountryGermany,
	India: CountryIndia,
	Indonesia: CountryIndonesia,
	Ireland: CountryIreland,
	Italy: CountryItaly,
	Mexico: CountryMexico,
	Netherlands: CountryNetherlands,
	NewZealand: CountryNewZealand,
	Nigeria: CountryNigeria,
	Norway: CountryNorway,
	Pakistan: CountryPakistan,
	Peru: CountryPeru,
	Philippines: CountryPhilippines,
	Poland: CountryPoland,
	Russia: CountryRussia,
	Singapore: CountrySingapore,
	SouthAfrica: CountrySouthAfrica,
	SouthKorea: CountrySouthKorea,
	Spain: CountrySpain,
	Sweden: CountrySweden,
	Turkey: CountryTurkey,
	UK: CountryUK,
	US: CountryUS,
	Ukraine: CountryUkraine,
	Vietnam: CountryVietnam
};

export enum DataType {
	Alphanumeric = 'Alphanumeric',
	AutoIncrement = 'AutoIncrement',
	Boolean = 'Boolean',
	CVV = 'CVV',
	City = 'City',
	Colour = 'Colour',
	Company = 'Company',
	Computed = 'Computed',
	Constant = 'Constant',
	Country = 'Country',
	Currency = 'Currency',
	Date = 'Date',
	Email = 'Email',
	GUID = 'GUID',
	IBAN = 'IBAN',
	LatLng = 'LatLng',
	List = 'List',
	Names = 'Names',
	NormalDistribution = 'NormalDistribution',
	NumberRange = 'NumberRange',
	PAN = 'PAN',
	PIN = 'PIN',
	Phone = 'Phone',
	PostalZip = 'PostalZip',
	Region = 'Region',
	Rut = 'Rut',
	StreetAddress = 'StreetAddress',
	TextFixed = 'TextFixed',
	TextRandom = 'TextRandom',
	Time = 'Time',
	Track1 = 'Track1',
	Track2 = 'Track2',
	URLs = 'URLs',
	WeightedList = 'WeightedList'
}

import { generate as AlphanumericG, defaultGenerationOptions as AlphanumericDGO } from './src/plugins/dataTypes/Alphanumeric/bundle';
import { generate as AutoIncrementG, defaultGenerationOptions as AutoIncrementDGO } from './src/plugins/dataTypes/AutoIncrement/bundle';
import { generate as BooleanG, defaultGenerationOptions as BooleanDGO } from './src/plugins/dataTypes/Boolean/bundle';
import { generate as CVVG, defaultGenerationOptions as CVVDGO } from './src/plugins/dataTypes/CVV/bundle';
import { generate as CityG, defaultGenerationOptions as CityDGO } from './src/plugins/dataTypes/City/bundle';
import { generate as ColourG, defaultGenerationOptions as ColourDGO } from './src/plugins/dataTypes/Colour/bundle';
import { generate as CompanyG, defaultGenerationOptions as CompanyDGO } from './src/plugins/dataTypes/Company/bundle';
import { generate as ComputedG, defaultGenerationOptions as ComputedDGO } from './src/plugins/dataTypes/Computed/bundle';
import { generate as ConstantG, defaultGenerationOptions as ConstantDGO } from './src/plugins/dataTypes/Constant/bundle';
import { generate as CountryG, defaultGenerationOptions as CountryDGO } from './src/plugins/dataTypes/Country/bundle';
import { generate as CurrencyG, defaultGenerationOptions as CurrencyDGO } from './src/plugins/dataTypes/Currency/bundle';
import { generate as DateG, defaultGenerationOptions as DateDGO } from './src/plugins/dataTypes/Date/bundle';
import { generate as EmailG, defaultGenerationOptions as EmailDGO } from './src/plugins/dataTypes/Email/bundle';
import { generate as GUIDG, defaultGenerationOptions as GUIDDGO } from './src/plugins/dataTypes/GUID/bundle';
import { generate as IBANG, defaultGenerationOptions as IBANDGO } from './src/plugins/dataTypes/IBAN/bundle';
import { generate as LatLngG, defaultGenerationOptions as LatLngDGO } from './src/plugins/dataTypes/LatLng/bundle';
import { generate as ListG, defaultGenerationOptions as ListDGO } from './src/plugins/dataTypes/List/bundle';
import { generate as NamesG, defaultGenerationOptions as NamesDGO } from './src/plugins/dataTypes/Names/bundle';
import { generate as NormalDistributionG, defaultGenerationOptions as NormalDistributionDGO } from './src/plugins/dataTypes/NormalDistribution/bundle';
import { generate as NumberRangeG, defaultGenerationOptions as NumberRangeDGO } from './src/plugins/dataTypes/NumberRange/bundle';
import { generate as PANG, defaultGenerationOptions as PANDGO } from './src/plugins/dataTypes/PAN/bundle';
import { generate as PING, defaultGenerationOptions as PINDGO } from './src/plugins/dataTypes/PIN/bundle';
import { generate as PhoneG, defaultGenerationOptions as PhoneDGO } from './src/plugins/dataTypes/Phone/bundle';
import { generate as PostalZipG, defaultGenerationOptions as PostalZipDGO } from './src/plugins/dataTypes/PostalZip/bundle';
import { generate as RegionG, defaultGenerationOptions as RegionDGO } from './src/plugins/dataTypes/Region/bundle';
import { generate as RutG, defaultGenerationOptions as RutDGO } from './src/plugins/dataTypes/Rut/bundle';
import { generate as StreetAddressG, defaultGenerationOptions as StreetAddressDGO } from './src/plugins/dataTypes/StreetAddress/bundle';
import { generate as TextFixedG, defaultGenerationOptions as TextFixedDGO } from './src/plugins/dataTypes/TextFixed/bundle';
import { generate as TextRandomG, defaultGenerationOptions as TextRandomDGO } from './src/plugins/dataTypes/TextRandom/bundle';
import { generate as TimeG, defaultGenerationOptions as TimeDGO } from './src/plugins/dataTypes/Time/bundle';
import { generate as Track1G, defaultGenerationOptions as Track1DGO } from './src/plugins/dataTypes/Track1/bundle';
import { generate as Track2G, defaultGenerationOptions as Track2DGO } from './src/plugins/dataTypes/Track2/bundle';
import { generate as URLsG, defaultGenerationOptions as URLsDGO } from './src/plugins/dataTypes/URLs/bundle';
import { generate as WeightedListG, defaultGenerationOptions as WeightedListDGO } from './src/plugins/dataTypes/WeightedList/bundle';


export const dataTypeGenerateMethods = {
	[DataType.Alphanumeric]: { generate: AlphanumericG, defaultGenerationOptions: AlphanumericDGO },
	[DataType.AutoIncrement]: { generate: AutoIncrementG, defaultGenerationOptions: AutoIncrementDGO },
	[DataType.Boolean]: { generate: BooleanG, defaultGenerationOptions: BooleanDGO },
	[DataType.CVV]: { generate: CVVG, defaultGenerationOptions: CVVDGO },
	[DataType.City]: { generate: CityG, defaultGenerationOptions: CityDGO },
	[DataType.Colour]: { generate: ColourG, defaultGenerationOptions: ColourDGO },
	[DataType.Company]: { generate: CompanyG, defaultGenerationOptions: CompanyDGO },
	[DataType.Computed]: { generate: ComputedG, defaultGenerationOptions: ComputedDGO },
	[DataType.Constant]: { generate: ConstantG, defaultGenerationOptions: ConstantDGO },
	[DataType.Country]: { generate: CountryG, defaultGenerationOptions: CountryDGO },
	[DataType.Currency]: { generate: CurrencyG, defaultGenerationOptions: CurrencyDGO },
	[DataType.Date]: { generate: DateG, defaultGenerationOptions: DateDGO },
	[DataType.Email]: { generate: EmailG, defaultGenerationOptions: EmailDGO },
	[DataType.GUID]: { generate: GUIDG, defaultGenerationOptions: GUIDDGO },
	[DataType.IBAN]: { generate: IBANG, defaultGenerationOptions: IBANDGO },
	[DataType.LatLng]: { generate: LatLngG, defaultGenerationOptions: LatLngDGO },
	[DataType.List]: { generate: ListG, defaultGenerationOptions: ListDGO },
	[DataType.Names]: { generate: NamesG, defaultGenerationOptions: NamesDGO },
	[DataType.NormalDistribution]: { generate: NormalDistributionG, defaultGenerationOptions: NormalDistributionDGO },
	[DataType.NumberRange]: { generate: NumberRangeG, defaultGenerationOptions: NumberRangeDGO },
	[DataType.PAN]: { generate: PANG, defaultGenerationOptions: PANDGO },
	[DataType.PIN]: { generate: PING, defaultGenerationOptions: PINDGO },
	[DataType.Phone]: { generate: PhoneG, defaultGenerationOptions: PhoneDGO },
	[DataType.PostalZip]: { generate: PostalZipG, defaultGenerationOptions: PostalZipDGO },
	[DataType.Region]: { generate: RegionG, defaultGenerationOptions: RegionDGO },
	[DataType.Rut]: { generate: RutG, defaultGenerationOptions: RutDGO },
	[DataType.StreetAddress]: { generate: StreetAddressG, defaultGenerationOptions: StreetAddressDGO },
	[DataType.TextFixed]: { generate: TextFixedG, defaultGenerationOptions: TextFixedDGO },
	[DataType.TextRandom]: { generate: TextRandomG, defaultGenerationOptions: TextRandomDGO },
	[DataType.Time]: { generate: TimeG, defaultGenerationOptions: TimeDGO },
	[DataType.Track1]: { generate: Track1G, defaultGenerationOptions: Track1DGO },
	[DataType.Track2]: { generate: Track2G, defaultGenerationOptions: Track2DGO },
	[DataType.URLs]: { generate: URLsG, defaultGenerationOptions: URLsDGO },
	[DataType.WeightedList]: { generate: WeightedListG, defaultGenerationOptions: WeightedListDGO }
};

import { GenerationOptionsType as AlphanumericGenerationOptions } from './src/plugins/dataTypes/Alphanumeric/bundle';
import { GenerationOptionsType as AutoIncrementGenerationOptions } from './src/plugins/dataTypes/AutoIncrement/bundle';
import { GenerationOptionsType as BooleanGenerationOptions } from './src/plugins/dataTypes/Boolean/bundle';
import { GenerationOptionsType as CVVGenerationOptions } from './src/plugins/dataTypes/CVV/bundle';
import { GenerationOptionsType as CityGenerationOptions } from './src/plugins/dataTypes/City/bundle';
import { GenerationOptionsType as ColourGenerationOptions } from './src/plugins/dataTypes/Colour/bundle';
import { GenerationOptionsType as CompanyGenerationOptions } from './src/plugins/dataTypes/Company/bundle';
import { GenerationOptionsType as ComputedGenerationOptions } from './src/plugins/dataTypes/Computed/bundle';
import { GenerationOptionsType as ConstantGenerationOptions } from './src/plugins/dataTypes/Constant/bundle';
import { GenerationOptionsType as CountryGenerationOptions } from './src/plugins/dataTypes/Country/bundle';
import { GenerationOptionsType as CurrencyGenerationOptions } from './src/plugins/dataTypes/Currency/bundle';
import { GenerationOptionsType as DateGenerationOptions } from './src/plugins/dataTypes/Date/bundle';
import { GenerationOptionsType as EmailGenerationOptions } from './src/plugins/dataTypes/Email/bundle';
import { GenerationOptionsType as GUIDGenerationOptions } from './src/plugins/dataTypes/GUID/bundle';
import { GenerationOptionsType as IBANGenerationOptions } from './src/plugins/dataTypes/IBAN/bundle';
import { GenerationOptionsType as LatLngGenerationOptions } from './src/plugins/dataTypes/LatLng/bundle';
import { GenerationOptionsType as ListGenerationOptions } from './src/plugins/dataTypes/List/bundle';
import { GenerationOptionsType as NamesGenerationOptions } from './src/plugins/dataTypes/Names/bundle';
import { GenerationOptionsType as NormalDistributionGenerationOptions } from './src/plugins/dataTypes/NormalDistribution/bundle';
import { GenerationOptionsType as NumberRangeGenerationOptions } from './src/plugins/dataTypes/NumberRange/bundle';
import { GenerationOptionsType as PANGenerationOptions } from './src/plugins/dataTypes/PAN/bundle';
import { GenerationOptionsType as PINGenerationOptions } from './src/plugins/dataTypes/PIN/bundle';
import { GenerationOptionsType as PhoneGenerationOptions } from './src/plugins/dataTypes/Phone/bundle';
import { GenerationOptionsType as PostalZipGenerationOptions } from './src/plugins/dataTypes/PostalZip/bundle';
import { GenerationOptionsType as RegionGenerationOptions } from './src/plugins/dataTypes/Region/bundle';
import { GenerationOptionsType as RutGenerationOptions } from './src/plugins/dataTypes/Rut/bundle';
import { GenerationOptionsType as StreetAddressGenerationOptions } from './src/plugins/dataTypes/StreetAddress/bundle';
import { GenerationOptionsType as TextFixedGenerationOptions } from './src/plugins/dataTypes/TextFixed/bundle';
import { GenerationOptionsType as TextRandomGenerationOptions } from './src/plugins/dataTypes/TextRandom/bundle';
import { GenerationOptionsType as TimeGenerationOptions } from './src/plugins/dataTypes/Time/bundle';
import { GenerationOptionsType as Track1GenerationOptions } from './src/plugins/dataTypes/Track1/bundle';
import { GenerationOptionsType as Track2GenerationOptions } from './src/plugins/dataTypes/Track2/bundle';
import { GenerationOptionsType as URLsGenerationOptions } from './src/plugins/dataTypes/URLs/bundle';
import { GenerationOptionsType as WeightedListGenerationOptions } from './src/plugins/dataTypes/WeightedList/bundle';

interface DataTypeOptionsMap {
	[DataType.Alphanumeric]: AlphanumericGenerationOptions;
	[DataType.AutoIncrement]: AutoIncrementGenerationOptions;
	[DataType.Boolean]: BooleanGenerationOptions;
	[DataType.CVV]: CVVGenerationOptions;
	[DataType.City]: CityGenerationOptions;
	[DataType.Colour]: ColourGenerationOptions;
	[DataType.Company]: CompanyGenerationOptions;
	[DataType.Computed]: ComputedGenerationOptions;
	[DataType.Constant]: ConstantGenerationOptions;
	[DataType.Country]: CountryGenerationOptions;
	[DataType.Currency]: CurrencyGenerationOptions;
	[DataType.Date]: DateGenerationOptions;
	[DataType.Email]: EmailGenerationOptions;
	[DataType.GUID]: GUIDGenerationOptions;
	[DataType.IBAN]: IBANGenerationOptions;
	[DataType.LatLng]: LatLngGenerationOptions;
	[DataType.List]: ListGenerationOptions;
	[DataType.Names]: NamesGenerationOptions;
	[DataType.NormalDistribution]: NormalDistributionGenerationOptions;
	[DataType.NumberRange]: NumberRangeGenerationOptions;
	[DataType.PAN]: PANGenerationOptions;
	[DataType.PIN]: PINGenerationOptions;
	[DataType.Phone]: PhoneGenerationOptions;
	[DataType.PostalZip]: PostalZipGenerationOptions;
	[DataType.Region]: RegionGenerationOptions;
	[DataType.Rut]: RutGenerationOptions;
	[DataType.StreetAddress]: StreetAddressGenerationOptions;
	[DataType.TextFixed]: TextFixedGenerationOptions;
	[DataType.TextRandom]: TextRandomGenerationOptions;
	[DataType.Time]: TimeGenerationOptions;
	[DataType.Track1]: Track1GenerationOptions;
	[DataType.Track2]: Track2GenerationOptions;
	[DataType.URLs]: URLsGenerationOptions;
	[DataType.WeightedList]: WeightedListGenerationOptions;
}

export type DataTypeGenerationOptions = {
	[K in DataType]: {
		plugin: K;
		title: string;
		settings: DataTypeOptionsMap[K];
		id?: string | number;
	}
}[DataType];

export enum ExportType {
	CSV = 'CSV',
	CSharp = 'CSharp',
	HTML = 'HTML',
	JSON = 'JSON',
	Javascript = 'Javascript',
	LDIF = 'LDIF',
	PHP = 'PHP',
	Perl = 'Perl',
	Python = 'Python',
	Ruby = 'Ruby',
	SQL = 'SQL',
	Typescript = 'Typescript',
	XML = 'XML'
}

import { GenerationOptionsType as CSVGenerationOptions } from './src/plugins/exportTypes/CSV/bundle';
import { GenerationOptionsType as CSharpGenerationOptions } from './src/plugins/exportTypes/CSharp/bundle';
import { GenerationOptionsType as HTMLGenerationOptions } from './src/plugins/exportTypes/HTML/bundle';
import { GenerationOptionsType as JSONGenerationOptions } from './src/plugins/exportTypes/JSON/bundle';
import { GenerationOptionsType as JavascriptGenerationOptions } from './src/plugins/exportTypes/Javascript/bundle';
import { GenerationOptionsType as LDIFGenerationOptions } from './src/plugins/exportTypes/LDIF/bundle';
import { GenerationOptionsType as PHPGenerationOptions } from './src/plugins/exportTypes/PHP/bundle';
import { GenerationOptionsType as PerlGenerationOptions } from './src/plugins/exportTypes/Perl/bundle';
import { GenerationOptionsType as PythonGenerationOptions } from './src/plugins/exportTypes/Python/bundle';
import { GenerationOptionsType as RubyGenerationOptions } from './src/plugins/exportTypes/Ruby/bundle';
import { GenerationOptionsType as SQLGenerationOptions } from './src/plugins/exportTypes/SQL/bundle';
import { GenerationOptionsType as TypescriptGenerationOptions } from './src/plugins/exportTypes/Typescript/bundle';
import { GenerationOptionsType as XMLGenerationOptions } from './src/plugins/exportTypes/XML/bundle';

interface ExportTypeOptionsMap {
	[ExportType.CSV]: CSVGenerationOptions;
	[ExportType.CSharp]: CSharpGenerationOptions;
	[ExportType.HTML]: HTMLGenerationOptions;
	[ExportType.JSON]: JSONGenerationOptions;
	[ExportType.Javascript]: JavascriptGenerationOptions;
	[ExportType.LDIF]: LDIFGenerationOptions;
	[ExportType.PHP]: PHPGenerationOptions;
	[ExportType.Perl]: PerlGenerationOptions;
	[ExportType.Python]: PythonGenerationOptions;
	[ExportType.Ruby]: RubyGenerationOptions;
	[ExportType.SQL]: SQLGenerationOptions;
	[ExportType.Typescript]: TypescriptGenerationOptions;
	[ExportType.XML]: XMLGenerationOptions;
}

export type ExportTypeGenerationOptions = {
	[K in ExportType]: {
		plugin: K;
		settings: ExportTypeOptionsMap[K];
	}
}[ExportType];

