/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import Alphanumeric from './src/plugins/dataTypes/Alphanumeric/config';
import AutoIncrement from './src/plugins/dataTypes/AutoIncrement/config';
import BitcoinAddress from './src/plugins/dataTypes/BitcoinAddress/config';
import Boolean from './src/plugins/dataTypes/Boolean/config';
import CVV from './src/plugins/dataTypes/CVV/config';
import City from './src/plugins/dataTypes/City/config';
import Colour from './src/plugins/dataTypes/Colour/config';
import Company from './src/plugins/dataTypes/Company/config';
import Computed from './src/plugins/dataTypes/Computed/config';
import Constant from './src/plugins/dataTypes/Constant/config';
import Country from './src/plugins/dataTypes/Country/config';
import Currency from './src/plugins/dataTypes/Currency/config';
import Date from './src/plugins/dataTypes/Date/config';
import Email from './src/plugins/dataTypes/Email/config';
import GUID from './src/plugins/dataTypes/GUID/config';
import IBAN from './src/plugins/dataTypes/IBAN/config';
import LatLng from './src/plugins/dataTypes/LatLng/config';
import List from './src/plugins/dataTypes/List/config';
import Names from './src/plugins/dataTypes/Names/config';
import NormalDistribution from './src/plugins/dataTypes/NormalDistribution/config';
import NumberRange from './src/plugins/dataTypes/NumberRange/config';
import OrganizationNumber from './src/plugins/dataTypes/OrganizationNumber/config';
import PAN from './src/plugins/dataTypes/PAN/config';
import PIN from './src/plugins/dataTypes/PIN/config';
import PersonalNumber from './src/plugins/dataTypes/PersonalNumber/config';
import Phone from './src/plugins/dataTypes/Phone/config';
import PostalZip from './src/plugins/dataTypes/PostalZip/config';
import Region from './src/plugins/dataTypes/Region/config';
import Rut from './src/plugins/dataTypes/Rut/config';
import SIRET from './src/plugins/dataTypes/SIRET/config';
import StreetAddress from './src/plugins/dataTypes/StreetAddress/config';
import TextFixed from './src/plugins/dataTypes/TextFixed/config';
import TextRandom from './src/plugins/dataTypes/TextRandom/config';
import Time from './src/plugins/dataTypes/Time/config';
import Track1 from './src/plugins/dataTypes/Track1/config';
import Track2 from './src/plugins/dataTypes/Track2/config';
import URLs from './src/plugins/dataTypes/URLs/config';
import WeightedList from './src/plugins/dataTypes/WeightedList/config';

export const dataTypes = {
	Alphanumeric,
	AutoIncrement,
	BitcoinAddress,
	Boolean,
	CVV,
	City,
	Colour,
	Company,
	Computed,
	Constant,
	Country,
	Currency,
	Date,
	Email,
	GUID,
	IBAN,
	LatLng,
	List,
	Names,
	NormalDistribution,
	NumberRange,
	OrganizationNumber,
	PAN,
	PIN,
	PersonalNumber,
	Phone,
	PostalZip,
	Region,
	Rut,
	SIRET,
	StreetAddress,
	TextFixed,
	TextRandom,
	Time,
	Track1,
	Track2,
	URLs,
	WeightedList
};

export type DataTypeFolder = keyof typeof dataTypes;

export const blacklistedDataTypeFolders = ['BitcoinAddress','OrganizationNumber','PersonalNumber','SIRET'];

import CSV from './src/plugins/exportTypes/CSV/config';
import CSharp from './src/plugins/exportTypes/CSharp/config';
import HTML from './src/plugins/exportTypes/HTML/config';
import JSON from './src/plugins/exportTypes/JSON/config';
import Javascript from './src/plugins/exportTypes/Javascript/config';
import LDIF from './src/plugins/exportTypes/LDIF/config';
import PHP from './src/plugins/exportTypes/PHP/config';
import Perl from './src/plugins/exportTypes/Perl/config';
import Python from './src/plugins/exportTypes/Python/config';
import Ruby from './src/plugins/exportTypes/Ruby/config';
import SQL from './src/plugins/exportTypes/SQL/config';
import Typescript from './src/plugins/exportTypes/Typescript/config';
import XML from './src/plugins/exportTypes/XML/config';

export const exportTypes = {
	CSV,
	CSharp,
	HTML,
	JSON,
	Javascript,
	LDIF,
	PHP,
	Perl,
	Python,
	Ruby,
	SQL,
	Typescript,
	XML
};

export type ExportTypeFolder = keyof typeof exportTypes;

import CountryAustralia from './src/plugins/countries/Australia/bundle';
import CountryAustria from './src/plugins/countries/Austria/bundle';
import CountryBelgium from './src/plugins/countries/Belgium/bundle';
import CountryBrazil from './src/plugins/countries/Brazil/bundle';
import CountryCanada from './src/plugins/countries/Canada/bundle';
import CountryChile from './src/plugins/countries/Chile/bundle';
import CountryChina from './src/plugins/countries/China/bundle';
import CountryColombia from './src/plugins/countries/Colombia/bundle';
import CountryCostaRica from './src/plugins/countries/CostaRica/bundle';
import CountryFrance from './src/plugins/countries/France/bundle';
import CountryGermany from './src/plugins/countries/Germany/bundle';
import CountryIndia from './src/plugins/countries/India/bundle';
import CountryIndonesia from './src/plugins/countries/Indonesia/bundle';
import CountryIreland from './src/plugins/countries/Ireland/bundle';
import CountryItaly from './src/plugins/countries/Italy/bundle';
import CountryMexico from './src/plugins/countries/Mexico/bundle';
import CountryNetherlands from './src/plugins/countries/Netherlands/bundle';
import CountryNewZealand from './src/plugins/countries/NewZealand/bundle';
import CountryNigeria from './src/plugins/countries/Nigeria/bundle';
import CountryNorway from './src/plugins/countries/Norway/bundle';
import CountryPakistan from './src/plugins/countries/Pakistan/bundle';
import CountryPeru from './src/plugins/countries/Peru/bundle';
import CountryPhilippines from './src/plugins/countries/Philippines/bundle';
import CountryPoland from './src/plugins/countries/Poland/bundle';
import CountryRussia from './src/plugins/countries/Russia/bundle';
import CountrySingapore from './src/plugins/countries/Singapore/bundle';
import CountrySouthAfrica from './src/plugins/countries/SouthAfrica/bundle';
import CountrySouthKorea from './src/plugins/countries/SouthKorea/bundle';
import CountrySpain from './src/plugins/countries/Spain/bundle';
import CountrySweden from './src/plugins/countries/Sweden/bundle';
import CountryTurkey from './src/plugins/countries/Turkey/bundle';
import CountryUK from './src/plugins/countries/UK/bundle';
import CountryUS from './src/plugins/countries/US/bundle';
import CountryUkraine from './src/plugins/countries/Ukraine/bundle';
import CountryVietnam from './src/plugins/countries/Vietnam/bundle';

export const countryList = ['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'CostaRica', 'France', 'Germany', 'India', 'Indonesia', 'Ireland', 'Italy', 'Mexico', 'Netherlands', 'NewZealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines', 'Poland', 'Russia', 'Singapore', 'SouthAfrica', 'SouthKorea', 'Spain', 'Sweden', 'Turkey', 'UK', 'US', 'Ukraine', 'Vietnam'];
export const countries = ['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'China', 'Colombia', 'CostaRica', 'France', 'Germany', 'India', 'Indonesia', 'Ireland', 'Italy', 'Mexico', 'Netherlands', 'NewZealand', 'Nigeria', 'Norway', 'Pakistan', 'Peru', 'Philippines', 'Poland', 'Russia', 'Singapore', 'SouthAfrica', 'SouthKorea', 'Spain', 'Sweden', 'Turkey', 'UK', 'US', 'Ukraine', 'Vietnam'] as const;
export const countryMethods = {
	Australia: CountryAustralia,
	Austria: CountryAustria,
	Belgium: CountryBelgium,
	Brazil: CountryBrazil,
	Canada: CountryCanada,
	Chile: CountryChile,
	China: CountryChina,
	Colombia: CountryColombia,
	CostaRica: CountryCostaRica,
	France: CountryFrance,
	Germany: CountryGermany,
	India: CountryIndia,
	Indonesia: CountryIndonesia,
	Ireland: CountryIreland,
	Italy: CountryItaly,
	Mexico: CountryMexico,
	Netherlands: CountryNetherlands,
	NewZealand: CountryNewZealand,
	Nigeria: CountryNigeria,
	Norway: CountryNorway,
	Pakistan: CountryPakistan,
	Peru: CountryPeru,
	Philippines: CountryPhilippines,
	Poland: CountryPoland,
	Russia: CountryRussia,
	Singapore: CountrySingapore,
	SouthAfrica: CountrySouthAfrica,
	SouthKorea: CountrySouthKorea,
	Spain: CountrySpain,
	Sweden: CountrySweden,
	Turkey: CountryTurkey,
	UK: CountryUK,
	US: CountryUS,
	Ukraine: CountryUkraine,
	Vietnam: CountryVietnam
};

export enum DataType {
	Alphanumeric = 'Alphanumeric',
	AutoIncrement = 'AutoIncrement',
	Boolean = 'Boolean',
	CVV = 'CVV',
	City = 'City',
	Colour = 'Colour',
	Company = 'Company',
	Computed = 'Computed',
	Constant = 'Constant',
	Country = 'Country',
	Currency = 'Currency',
	Date = 'Date',
	Email = 'Email',
	GUID = 'GUID',
	IBAN = 'IBAN',
	LatLng = 'LatLng',
	List = 'List',
	Names = 'Names',
	NormalDistribution = 'NormalDistribution',
	NumberRange = 'NumberRange',
	PAN = 'PAN',
	PIN = 'PIN',
	Phone = 'Phone',
	PostalZip = 'PostalZip',
	Region = 'Region',
	Rut = 'Rut',
	StreetAddress = 'StreetAddress',
	TextFixed = 'TextFixed',
	TextRandom = 'TextRandom',
	Time = 'Time',
	Track1 = 'Track1',
	Track2 = 'Track2',
	URLs = 'URLs',
	WeightedList = 'WeightedList'
}

// import { generate as AlphanumericGenerate } from './src/plugins/dataTypes/Alphanumeric/Alphanumeric.generate';
// import { generate as AutoIncrementGenerate } from './src/plugins/dataTypes/AutoIncrement/AutoIncrement.generate';
// import { generate as BooleanGenerate } from './src/plugins/dataTypes/Boolean/Boolean.generate';
// import { generate as CVVGenerate } from './src/plugins/dataTypes/CVV/CVV.generate';
// import { generate as CityGenerate } from './src/plugins/dataTypes/City/City.generate';
// import { generate as ColourGenerate } from './src/plugins/dataTypes/Colour/Colour.generate';
// import { generate as CompanyGenerate } from './src/plugins/dataTypes/Company/Company.generate';
// import { generate as ComputedGenerate } from './src/plugins/dataTypes/Computed/Computed.generate';
// import { generate as ConstantGenerate } from './src/plugins/dataTypes/Constant/Constant.generate';
// import { generate as CountryGenerate } from './src/plugins/dataTypes/Country/Country.generate';
// import { generate as CurrencyGenerate } from './src/plugins/dataTypes/Currency/Currency.generate';
// import { generate as DateGenerate } from './src/plugins/dataTypes/Date/Date.generate';
// import { generate as EmailGenerate } from './src/plugins/dataTypes/Email/Email.generate';
// import { generate as GUIDGenerate } from './src/plugins/dataTypes/GUID/GUID.generate';
// import { generate as IBANGenerate } from './src/plugins/dataTypes/IBAN/IBAN.generate';
// import { generate as LatLngGenerate } from './src/plugins/dataTypes/LatLng/LatLng.generate';
// import { generate as ListGenerate } from './src/plugins/dataTypes/List/List.generate';
import { generate as NamesGenerate } from './src/plugins/dataTypes/Names/Names.generate';
// import { generate as NormalDistributionGenerate } from './src/plugins/dataTypes/NormalDistribution/NormalDistribution.generate';
// import { generate as NumberRangeGenerate } from './src/plugins/dataTypes/NumberRange/NumberRange.generate';
// import { generate as PANGenerate } from './src/plugins/dataTypes/PAN/PAN.generate';
// import { generate as PINGenerate } from './src/plugins/dataTypes/PIN/PIN.generate';
// import { generate as PhoneGenerate } from './src/plugins/dataTypes/Phone/Phone.generate';
// import { generate as PostalZipGenerate } from './src/plugins/dataTypes/PostalZip/PostalZip.generate';
// import { generate as RegionGenerate } from './src/plugins/dataTypes/Region/Region.generate';
// import { generate as RutGenerate } from './src/plugins/dataTypes/Rut/Rut.generate';
// import { generate as StreetAddressGenerate } from './src/plugins/dataTypes/StreetAddress/StreetAddress.generate';
// import { generate as TextFixedGenerate } from './src/plugins/dataTypes/TextFixed/TextFixed.generate';
// import { generate as TextRandomGenerate } from './src/plugins/dataTypes/TextRandom/TextRandom.generate';
// import { generate as TimeGenerate } from './src/plugins/dataTypes/Time/Time.generate';
// import { generate as Track1Generate } from './src/plugins/dataTypes/Track1/Track1.generate';
// import { generate as Track2Generate } from './src/plugins/dataTypes/Track2/Track2.generate';
// import { generate as URLsGenerate } from './src/plugins/dataTypes/URLs/URLs.generate';
// import { generate as WeightedListGenerate } from './src/plugins/dataTypes/WeightedList/WeightedList.generate';


export const dataTypeGenerateMethods = {
	// [DataType.Alphanumeric]: AlphanumericGenerate,
	// [DataType.AutoIncrement]: AutoIncrementGenerate,
	// [DataType.Boolean]: BooleanGenerate,
	// [DataType.CVV]: CVVGenerate,
	// [DataType.City]: CityGenerate,
	// [DataType.Colour]: ColourGenerate,
	// [DataType.Company]: CompanyGenerate,
	// [DataType.Computed]: ComputedGenerate,
	// [DataType.Constant]: ConstantGenerate,
	// [DataType.Country]: CountryGenerate,
	// [DataType.Currency]: CurrencyGenerate,
	// [DataType.Date]: DateGenerate,
	// [DataType.Email]: EmailGenerate,
	// [DataType.GUID]: GUIDGenerate,
	// [DataType.IBAN]: IBANGenerate,
	// [DataType.LatLng]: LatLngGenerate,
	// [DataType.List]: ListGenerate,
	[DataType.Names]: NamesGenerate,
	// [DataType.NormalDistribution]: NormalDistributionGenerate,
	// [DataType.NumberRange]: NumberRangeGenerate,
	// [DataType.PAN]: PANGenerate,
	// [DataType.PIN]: PINGenerate,
	// [DataType.Phone]: PhoneGenerate,
	// [DataType.PostalZip]: PostalZipGenerate,
	// [DataType.Region]: RegionGenerate,
	// [DataType.Rut]: RutGenerate,
	// [DataType.StreetAddress]: StreetAddressGenerate,
	// [DataType.TextFixed]: TextFixedGenerate,
	// [DataType.TextRandom]: TextRandomGenerate,
	// [DataType.Time]: TimeGenerate,
	// [DataType.Track1]: Track1Generate,
	// [DataType.Track2]: Track2Generate,
	// [DataType.URLs]: URLsGenerate,
	// [DataType.WeightedList]: WeightedListGenerate
};

import { GenerationOptionsType as AlphanumericGenerationOptions } from './src/plugins/dataTypes/Alphanumeric/bundle';
import { GenerationOptionsType as AutoIncrementGenerationOptions } from './src/plugins/dataTypes/AutoIncrement/bundle';
import { GenerationOptionsType as BooleanGenerationOptions } from './src/plugins/dataTypes/Boolean/bundle';
import { GenerationOptionsType as CVVGenerationOptions } from './src/plugins/dataTypes/CVV/bundle';
import { GenerationOptionsType as CityGenerationOptions } from './src/plugins/dataTypes/City/bundle';
import { GenerationOptionsType as ColourGenerationOptions } from './src/plugins/dataTypes/Colour/bundle';
import { GenerationOptionsType as CompanyGenerationOptions } from './src/plugins/dataTypes/Company/bundle';
import { GenerationOptionsType as ComputedGenerationOptions } from './src/plugins/dataTypes/Computed/bundle';
import { GenerationOptionsType as ConstantGenerationOptions } from './src/plugins/dataTypes/Constant/bundle';
import { GenerationOptionsType as CountryGenerationOptions } from './src/plugins/dataTypes/Country/bundle';
import { GenerationOptionsType as CurrencyGenerationOptions } from './src/plugins/dataTypes/Currency/bundle';
import { GenerationOptionsType as DateGenerationOptions } from './src/plugins/dataTypes/Date/bundle';
import { GenerationOptionsType as EmailGenerationOptions } from './src/plugins/dataTypes/Email/bundle';
import { GenerationOptionsType as GUIDGenerationOptions } from './src/plugins/dataTypes/GUID/bundle';
import { GenerationOptionsType as IBANGenerationOptions } from './src/plugins/dataTypes/IBAN/bundle';
import { GenerationOptionsType as LatLngGenerationOptions } from './src/plugins/dataTypes/LatLng/bundle';
import { GenerationOptionsType as ListGenerationOptions } from './src/plugins/dataTypes/List/bundle';
import { GenerationOptionsType as NamesGenerationOptions } from './src/plugins/dataTypes/Names/bundle';
import { GenerationOptionsType as NormalDistributionGenerationOptions } from './src/plugins/dataTypes/NormalDistribution/bundle';
import { GenerationOptionsType as NumberRangeGenerationOptions } from './src/plugins/dataTypes/NumberRange/bundle';
import { GenerationOptionsType as PANGenerationOptions } from './src/plugins/dataTypes/PAN/bundle';
import { GenerationOptionsType as PINGenerationOptions } from './src/plugins/dataTypes/PIN/bundle';
import { GenerationOptionsType as PhoneGenerationOptions } from './src/plugins/dataTypes/Phone/bundle';
import { GenerationOptionsType as PostalZipGenerationOptions } from './src/plugins/dataTypes/PostalZip/bundle';
import { GenerationOptionsType as RegionGenerationOptions } from './src/plugins/dataTypes/Region/bundle';
import { GenerationOptionsType as RutGenerationOptions } from './src/plugins/dataTypes/Rut/bundle';
import { GenerationOptionsType as StreetAddressGenerationOptions } from './src/plugins/dataTypes/StreetAddress/bundle';
import { GenerationOptionsType as TextFixedGenerationOptions } from './src/plugins/dataTypes/TextFixed/bundle';
import { GenerationOptionsType as TextRandomGenerationOptions } from './src/plugins/dataTypes/TextRandom/bundle';
import { GenerationOptionsType as TimeGenerationOptions } from './src/plugins/dataTypes/Time/bundle';
import { GenerationOptionsType as Track1GenerationOptions } from './src/plugins/dataTypes/Track1/bundle';
import { GenerationOptionsType as Track2GenerationOptions } from './src/plugins/dataTypes/Track2/bundle';
import { GenerationOptionsType as URLsGenerationOptions } from './src/plugins/dataTypes/URLs/bundle';
import { GenerationOptionsType as WeightedListGenerationOptions } from './src/plugins/dataTypes/WeightedList/bundle';

interface DataTypeOptionsMap {
	[DataType.Alphanumeric]: AlphanumericGenerationOptions;
	[DataType.AutoIncrement]: AutoIncrementGenerationOptions;
	[DataType.Boolean]: BooleanGenerationOptions;
	[DataType.CVV]: CVVGenerationOptions;
	[DataType.City]: CityGenerationOptions;
	[DataType.Colour]: ColourGenerationOptions;
	[DataType.Company]: CompanyGenerationOptions;
	[DataType.Computed]: ComputedGenerationOptions;
	[DataType.Constant]: ConstantGenerationOptions;
	[DataType.Country]: CountryGenerationOptions;
	[DataType.Currency]: CurrencyGenerationOptions;
	[DataType.Date]: DateGenerationOptions;
	[DataType.Email]: EmailGenerationOptions;
	[DataType.GUID]: GUIDGenerationOptions;
	[DataType.IBAN]: IBANGenerationOptions;
	[DataType.LatLng]: LatLngGenerationOptions;
	[DataType.List]: ListGenerationOptions;
	[DataType.Names]: NamesGenerationOptions;
	[DataType.NormalDistribution]: NormalDistributionGenerationOptions;
	[DataType.NumberRange]: NumberRangeGenerationOptions;
	[DataType.PAN]: PANGenerationOptions;
	[DataType.PIN]: PINGenerationOptions;
	[DataType.Phone]: PhoneGenerationOptions;
	[DataType.PostalZip]: PostalZipGenerationOptions;
	[DataType.Region]: RegionGenerationOptions;
	[DataType.Rut]: RutGenerationOptions;
	[DataType.StreetAddress]: StreetAddressGenerationOptions;
	[DataType.TextFixed]: TextFixedGenerationOptions;
	[DataType.TextRandom]: TextRandomGenerationOptions;
	[DataType.Time]: TimeGenerationOptions;
	[DataType.Track1]: Track1GenerationOptions;
	[DataType.Track2]: Track2GenerationOptions;
	[DataType.URLs]: URLsGenerationOptions;
	[DataType.WeightedList]: WeightedListGenerationOptions;
}

export type DataTypeGenerationOptions = {
	[K in DataType]: {
		plugin: K;
		title: string;
		settings: DataTypeOptionsMap[K];
		id?: string | number;
	}
}[DataType];

export enum ExportType {
	CSV = 'CSV',
	CSharp = 'CSharp',
	HTML = 'HTML',
	JSON = 'JSON',
	Javascript = 'Javascript',
	LDIF = 'LDIF',
	PHP = 'PHP',
	Perl = 'Perl',
	Python = 'Python',
	Ruby = 'Ruby',
	SQL = 'SQL',
	Typescript = 'Typescript',
	XML = 'XML'
}

import { GenerationOptionsType as CSVGenerationOptions } from './src/plugins/exportTypes/CSV/bundle';
import { GenerationOptionsType as CSharpGenerationOptions } from './src/plugins/exportTypes/CSharp/bundle';
import { GenerationOptionsType as HTMLGenerationOptions } from './src/plugins/exportTypes/HTML/bundle';
import { GenerationOptionsType as JSONGenerationOptions } from './src/plugins/exportTypes/JSON/bundle';
import { GenerationOptionsType as JavascriptGenerationOptions } from './src/plugins/exportTypes/Javascript/bundle';
import { GenerationOptionsType as LDIFGenerationOptions } from './src/plugins/exportTypes/LDIF/bundle';
import { GenerationOptionsType as PHPGenerationOptions } from './src/plugins/exportTypes/PHP/bundle';
import { GenerationOptionsType as PerlGenerationOptions } from './src/plugins/exportTypes/Perl/bundle';
import { GenerationOptionsType as PythonGenerationOptions } from './src/plugins/exportTypes/Python/bundle';
import { GenerationOptionsType as RubyGenerationOptions } from './src/plugins/exportTypes/Ruby/bundle';
import { GenerationOptionsType as SQLGenerationOptions } from './src/plugins/exportTypes/SQL/bundle';
import { GenerationOptionsType as TypescriptGenerationOptions } from './src/plugins/exportTypes/Typescript/bundle';
import { GenerationOptionsType as XMLGenerationOptions } from './src/plugins/exportTypes/XML/bundle';

interface ExportTypeOptionsMap {
	[ExportType.CSV]: CSVGenerationOptions;
	[ExportType.CSharp]: CSharpGenerationOptions;
	[ExportType.HTML]: HTMLGenerationOptions;
	[ExportType.JSON]: JSONGenerationOptions;
	[ExportType.Javascript]: JavascriptGenerationOptions;
	[ExportType.LDIF]: LDIFGenerationOptions;
	[ExportType.PHP]: PHPGenerationOptions;
	[ExportType.Perl]: PerlGenerationOptions;
	[ExportType.Python]: PythonGenerationOptions;
	[ExportType.Ruby]: RubyGenerationOptions;
	[ExportType.SQL]: SQLGenerationOptions;
	[ExportType.Typescript]: TypescriptGenerationOptions;
	[ExportType.XML]: XMLGenerationOptions;
}

export type ExportTypeGenerationOptions = {
	[K in ExportType]: {
		plugin: K;
		settings: ExportTypeOptionsMap[K];
	}
}[ExportType];

