const fs = require('fs');

module.exports = function (grunt) {	
	const dataTypesFolder = 'src/plugins/dataTypes';
	const locales = ['en'];

	const generateI18nBundles = () => {
		locales.forEach((locale) => {
			const coreLocaleStrings = fs.readFileSync(`src/i18n/${locale}.json`);
			const dtImports = getDataTypeLocaleFilePaths(locale);

			generateLocaleFileTemplate(locale, coreLocaleStrings, dtImports);
		});
	};

	const getDataTypeLocaleFilePaths = (locale) => {
		const dataTypeFolders = fs.readdirSync(dataTypesFolder);
		const dtImports = {};
		dataTypeFolders.forEach((folder) => {
			const localeFile = `${dataTypesFolder}/${folder}/i18n/${locale}.json`;
			if (fs.existsSync(localeFile)) {
				dtImports[folder] = `const ${folder} = ${fs.readFileSync(localeFile, 'utf8').trim()};`;
			}
		});
		return dtImports;
	};

	const generateLocaleFileTemplate = (locale, coreLocaleStrings, dtImports) => {
		const template = `
// DO NOT EDIT. This file is generated by a Grunt task.
// ----------------------------------------------------

(function() { 
const coreLocaleStrings = ${coreLocaleStrings};

${Object.values(dtImports).join('\n')}

const i18n = {
	core: {
		...coreLocaleStrings
	},
	dataTypes: {
		${Object.keys(dtImports).join(',\n\t\t\t')}
	},
	exportTypes: {

	}
};

// load the locale info via an exposed global
window.gd.localeLoaded(i18n);
})();`;

		fs.writeFileSync(`./dist/${locale}.js`, template);
	};

	grunt.initConfig({
		cssmin: {
			options: {
				mergeIntoShorthands: false,
				roundingPrecision: -1
			},
			target: {
				files: {
					'dist/styles.css': [
						'src/resources/codemirror.css',
						'src/resources/ambience.css',
						'src/resources/cobalt.css',
						'src/resources/darcula.css',
						'src/resources/elegant.css',
						'src/resources/lucario.css'
					]
				}
			}
		}
	});

	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.registerTask('default', ['cssmin']);
	grunt.registerTask('i18n', generateI18nBundles);
};