module.exports = function(grunt) {
	"use strict";


	var config = {
		pkg: grunt.file.readJSON('package.json'),

		uglify: {
			coreJS: {
				files: {
					'cache/core.js': [
						'resources/libs/codemirror/lib/codemirror.min.js',
						'resources/scripts/libs/jquery.min.js',
						'resources/scripts/libs/chosen.jquery.min.js',
						'resources/scripts/libs/require.js',
						'resources/scripts/requireConfig.js',
						'resources/scripts/libs/spinners.js',

						// pity, but now everyone gets them <!--[if lt IE 9]>
						'resources/scripts/libs/html5shiv.js',
						'resources/scripts/libs/excanvas.js'
					]
				},
				options: {
					report: "min",
					compress: true
				}
			}
		},

		cssmin: {
			target: {
				files: {
					'cache/core.css': [
						'resources/themes/classic/compiled/styles.css',
						'resources/css/smoothness/jquery-ui.min.css',
						'resources/css/chosen/chosen.css',
						'resources/css/tablesorter.theme.css',
						'resources/libs/codemirror/lib/codemirror.css'
					]
				}
			}
		},

		requirejs: {
			compile: {
				options: {
					name: "appStartGenerated",
					baseUrl: "resources/scripts",
					mainConfigFile: "resources/scripts/requireConfig.js",
					out: "cache/appStartGenerated.min.js"
				}
			}
		},

		md5: {
			prod: {
				files: {

				},
				options: {
					after: function(fileChanges) {
						//config.template.prod.options.data.APP_START_PATH = fileChanges[0].newPath;
					}
				}
			}
		}
	};

	grunt.initConfig(config);

	grunt.loadNpmTasks('grunt-contrib-requirejs');
	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-md5');
	grunt.loadNpmTasks('grunt-template');
	grunt.loadNpmTasks('grunt-contrib-cssmin');

	/**
	 * The default - and only - Grunt task simply recreates all the bundled resources. It doesn't alter the actual
	 * script at all. To use these bundled resources you need to add a $useMinifiedResources = true; var to your
	 * settings.php file.
	 */
	grunt.registerTask('default', [

		// uglify the core CSS + JS
		'uglify',
		'cssmin',

		// generate the requireJS bundle containing all modules + core. This relies on there being a
		// /cache/appStartStatic file having been auto-generated by the script first. That file is generated every
		// time you click the "Reset Plugins" link
		'requirejs'

		// now create md5 versions of the main minified file, which (re)-generates the /cache/minifiedResourcePaths.php file
		// with the latest file mapping
		//'md5'
	]);
};