packages:
  - apps/*
  - packages/*
catalog:
  "@apollo/client": ^4.0.0
  "@apollo/server": ^5.2.0
  "@as-integrations/express5": ^1.1.2
  "@babel/core": ^7.7.4
  "@babel/plugin-proposal-class-properties": ^7.10.4
  "@babel/plugin-syntax-dynamic-import": ^7.8.3
  "@babel/preset-env": ^7.7.4
  "@babel/preset-react": ^7.7.4
  "@babel/runtime": ^7.28.4
  "@date-io/date-fns": ^1.3.13
  "@dnd-kit/core": ^6.3.1
  "@dnd-kit/modifiers": ^9.0.0
  "@dnd-kit/sortable": ^10.0.0
  "@dnd-kit/utilities": ^3.2.2
  "@eddeee888/gcg-typescript-resolver-files": ^0.15.0
  "@emotion/styled": ^11.14.1
  "@esbuild-plugins/tsconfig-paths": ^0.0.4
  "@graphql-codegen/cli": ^6.1.0
  "@griffel/react": ^1.5.32
  "@mui/icons-material": ^7.3.5
  "@mui/lab": ^7.0.1-beta.19
  "@mui/material": ^7.3.5
  "@mui/styles": ^6.4.8
  "@mui/system": ^7.3.5
  "@mui/x-date-pickers": ^8.10.2
  "@react-hook/throttle": ^2.2.0
  "@reduxjs/toolkit": ^2.8.2
  "@rollup/plugin-babel": ^6.1.0
  "@rollup/plugin-commonjs": ^15.1.0
  "@rollup/plugin-node-resolve": ^13.3.0
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-typescript": ^12.3.0
  "@storybook/addon-a11y": ^10.1.9
  "@storybook/addon-docs": ^10.1.9
  "@storybook/react": 10.1.9
  "@stylistic/eslint-plugin-js": ^3.1.0
  "@testing-library/dom": ^10.4.1
  "@testing-library/react": ^16.3.0
  "@types/codemirror": ^0.0.99
  "@types/cookie-parser": ^1.4.10
  "@types/cors": ^2.8.19
  "@types/express": ^5.0.6
  "@types/jest": ^30.0.0
  "@types/js-cookie": ^3.0.5
  "@types/jsonwebtoken": ^9.0.10
  "@types/loadable__component": ^5.13.8
  "@types/node": ^20.19.11
  "@types/nanoid": 3.0.0
  "@types/nodemailer": ^7.0.4
  "@types/randomcolor": ^0.5.9
  "@types/react": ^18.3.27
  "@types/react-copy-to-clipboard": ^5.0.7
  "@types/react-dom": ^18.3.7
  "@types/react-input-autosize": ^2.2.4
  "@types/reactour": ^1.18.5
  "@types/redux-testkit": ^1.0.8
  "@typescript-eslint/eslint-plugin": ^8.47.0
  "@typescript-eslint/parser": ^8.47.0
  "@uidotdev/usehooks": ^2.4.1
  ansi-colors: ^4.1.3
  assert: ^2.1.0
  babel-eslint: ^10.0.3
  babel-loader: ^8.0.6
  babel-preset-airbnb: ^4.4.0
  bcryptjs: ^3.0.3
  browserify-zlib: ^0.2.0
  case-sensitive-paths-webpack-plugin: ^2.4.0
  cli-progress: ^3.11.2
  codemirror: ^5.58.2
  cookie-parser: ^1.4.5
  copy-webpack-plugin: ^13.0.1
  copyfiles: ^2.4.1
  cors: ^2.8.5
  cross-fetch: ^3.1.5
  crypto-browserify: ^3.12.1
  date-fns: ^2.17.0
  dotenv: ^8.2.0
  eslint: ^8.52.0
  eslint-config-airbnb: ^19.0.4
  eslint-config-airbnb-base: ^15.0.0
  eslint-plugin-import: ^2.27.5
  eslint-plugin-jsx-a11y: ^6.7.1
  eslint-plugin-react: ^7.32.0
  eslint-webpack-plugin: ^4.0.1
  express: ^5.2.1
  google-auth-library: ^10.5.0
  googleapis: ^169.0.0
  graphql: ^16.12.0
  graphql-scalars: ^1.25.0
  grunt: ^1.6.1
  grunt-cli: ^1.3.2
  grunt-contrib-clean: ^2.0.0
  grunt-contrib-copy: ^1.0.0
  grunt-contrib-cssmin: ^5.0.0
  grunt-contrib-uglify: ^5.2.2
  grunt-contrib-watch: ^1.1.0
  grunt-md5: ^0.1.12
  grunt-shell: ^4.0.0
  history: ^5.3.0
  html-webpack-plugin: ^5.5.0
  immer: ^11.0.1
  jest: ^30.2.0
  jest-cli: ^30.2.0
  jest-css-modules: ^2.1.0
  jest-environment-jsdom: ^29.4.3
  js-cookie: ^3.0.5
  json-loader: 0.5.4
  jsonwebtoken: ^9.0.3
  md5-file: ^5.0.0
  mini-css-extract-plugin: ^2.9.4
  mysql2: ^3.9.8
  nanoid: ^3.3.4
  nodemailer: ^7.0.12
  nodemon: ^3.1.11
  notistack: ^3.0.2
  npm-run-all: ^4.1.5
  os-browserify: ^0.3.0
  path-browserify: ^1.0.1
  prettier: ^3.4.2
  prettier-eslint: ^16.3.0
  pretty-bytes: ^7.1.0
  process: ^0.11.10
  promise: 7.1.1
  randomcolor: ^0.6.2
  react: ^18.3.1
  react-codemirror2: ^8.0.1
  react-copy-to-clipboard: ^5.1.0
  react-countup: ^6.5.3
  react-dom: ^18.3.1
  react-hooks-window-size: ^0.3.0
  react-input-autosize: ^3.0.0
  react-number-format: 5.4.4
  react-redux: ^9.2.0
  react-router: ^7.12.0
  react-router-dom: ^7.12.0
  react-select: ^5.10.2
  react-split-pane: ^3.0.5
  reactour: ^1.19.4
  recharts: ^3.6.0
  redux: ^5.0.1
  redux-testkit: ^1.0.6
  reselect: ^5.1.1
  rimraf: ^6.0.1
  rollup: ^2.31.0
  rollup-plugin-strip-exports: ^2.0.6
  rollup-plugin-terser: ^7.0.2
  rollup-plugin-typescript2: ^0.27.1
  rxjs: ^7.3.0
  sass: ^1.49.9
  semver: 7.7.3
  sequelize: ^6.37.7
  sinon: ^21.0.0
  storybook: ^10.1.10
  storybook-react-rsbuild: ^3.1.0
  stream-browserify: ^3.0.0
  styled-components: ^4.0.0
  terser-webpack-plugin: ^5.3.14
  ts-jest: ^29.2.5
  ts-loader: ^9.4.2
  ts-node: ^10.9.2
  tsconfig-paths: 4.1.1
  turbo: ^2.3.3
  typescript: ^5.9.3
  underscore: ^1.13.7
  use-onclickoutside: ^0.4.1
  vm-browserify: ^1.1.2
  webpack: ^5.103.0
  webpack-bundle-analyzer: ^5.0.1
  webpack-cli: ^6.0.1
  webpack-dev-middleware: ^7.4.5
  webpack-dev-server: ^5.2.2
  webpack-hot-middleware: ^2.26.1
  webpack-manifest-plugin: ^6.0.1
  yargs: ^17.6.2
