/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	userdoc: [
		{
			type: 'doc',
			id: 'userdoc/intro'
		},
		{
			type: 'category',
			label: 'About',
			items: [
				{
					type: 'doc',
					id: 'userdoc/about/purpose'
				},
				{
					type: 'doc',
					id: 'userdoc/about/versionComparison'
				},
				{
					type: 'doc',
					id: 'userdoc/about/website'
				},
			],
		},
		{
			type: 'category',
			label: 'Installation',
			items: [
				{
					type: 'autogenerated',
					dirName: 'userdoc/installation'
				},
			],
		},
		{
			type: 'doc',
			label: 'v3 doc',
			id: 'userdoc/v3'
		}
	],
	developerdoc: [
		{
			type: 'autogenerated',
			dirName: 'developerdoc'
		}
	]
};

module.exports = sidebars;
