/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import { DataType, ExportType } from '../client/_plugins';
import { generate as AlphanumericG } from '../client/src/plugins/dataTypes/Alphanumeric/Alphanumeric.generate';
import { defaultGenerationOptions as AlphanumericDGO } from '../client/src/plugins/dataTypes/Alphanumeric/Alphanumeric.state';
import { generate as AutoIncrementG } from '../client/src/plugins/dataTypes/AutoIncrement/AutoIncrement.generate';
import { defaultGenerationOptions as AutoIncrementDGO } from '../client/src/plugins/dataTypes/AutoIncrement/AutoIncrement.state';
import { generate as BooleanG } from '../client/src/plugins/dataTypes/Boolean/Boolean.generate';
import { defaultGenerationOptions as BooleanDGO } from '../client/src/plugins/dataTypes/Boolean/Boolean.state';
import { generate as CVVG } from '../client/src/plugins/dataTypes/CVV/CVV.generate';
import { defaultGenerationOptions as CVVDGO } from '../client/src/plugins/dataTypes/CVV/CVV.state';
import { generate as CityG } from '../client/src/plugins/dataTypes/City/City.generate';
import { defaultGenerationOptions as CityDGO } from '../client/src/plugins/dataTypes/City/City.state';
import { generate as ColourG } from '../client/src/plugins/dataTypes/Colour/Colour.generate';
import { defaultGenerationOptions as ColourDGO } from '../client/src/plugins/dataTypes/Colour/Colour.state';
import { generate as CompanyG } from '../client/src/plugins/dataTypes/Company/Company.generate';
import { defaultGenerationOptions as CompanyDGO } from '../client/src/plugins/dataTypes/Company/Company.state';
import { generate as ComputedG } from '../client/src/plugins/dataTypes/Computed/Computed.generate';
import { defaultGenerationOptions as ComputedDGO } from '../client/src/plugins/dataTypes/Computed/Computed.state';
import { generate as ConstantG } from '../client/src/plugins/dataTypes/Constant/Constant.generate';
import { defaultGenerationOptions as ConstantDGO } from '../client/src/plugins/dataTypes/Constant/Constant.state';
import { generate as CountryG } from '../client/src/plugins/dataTypes/Country/Country.generate';
import { defaultGenerationOptions as CountryDGO } from '../client/src/plugins/dataTypes/Country/Country.state';
import { generate as CurrencyG } from '../client/src/plugins/dataTypes/Currency/Currency.generate';
import { defaultGenerationOptions as CurrencyDGO } from '../client/src/plugins/dataTypes/Currency/Currency.state';
import { generate as DateG } from '../client/src/plugins/dataTypes/Date/Date.generate';
import { defaultGenerationOptions as DateDGO } from '../client/src/plugins/dataTypes/Date/Date.state';
import { generate as EmailG } from '../client/src/plugins/dataTypes/Email/Email.generate';
import { defaultGenerationOptions as EmailDGO } from '../client/src/plugins/dataTypes/Email/Email.state';
import { generate as GUIDG } from '../client/src/plugins/dataTypes/GUID/GUID.generate';
import { defaultGenerationOptions as GUIDDGO } from '../client/src/plugins/dataTypes/GUID/GUID.state';
import { generate as IBANG } from '../client/src/plugins/dataTypes/IBAN/IBAN.generate';
import { defaultGenerationOptions as IBANDGO } from '../client/src/plugins/dataTypes/IBAN/IBAN.state';
import { generate as LatLngG } from '../client/src/plugins/dataTypes/LatLng/LatLng.generate';
import { defaultGenerationOptions as LatLngDGO } from '../client/src/plugins/dataTypes/LatLng/LatLng.state';
import { generate as ListG } from '../client/src/plugins/dataTypes/List/List.generate';
import { defaultGenerationOptions as ListDGO } from '../client/src/plugins/dataTypes/List/List.state';
import { generate as NamesG } from '../client/src/plugins/dataTypes/Names/Names.generate';
import { defaultGenerationOptions as NamesDGO } from '../client/src/plugins/dataTypes/Names/Names.state';
import { generate as NormalDistributionG } from '../client/src/plugins/dataTypes/NormalDistribution/NormalDistribution.generate';
import { defaultGenerationOptions as NormalDistributionDGO } from '../client/src/plugins/dataTypes/NormalDistribution/NormalDistribution.state';
import { generate as NumberRangeG } from '../client/src/plugins/dataTypes/NumberRange/NumberRange.generate';
import { defaultGenerationOptions as NumberRangeDGO } from '../client/src/plugins/dataTypes/NumberRange/NumberRange.state';
import { generate as PANG } from '../client/src/plugins/dataTypes/PAN/PAN.generate';
import { defaultGenerationOptions as PANDGO } from '../client/src/plugins/dataTypes/PAN/PAN.state';
import { generate as PING } from '../client/src/plugins/dataTypes/PIN/PIN.generate';
import { defaultGenerationOptions as PINDGO } from '../client/src/plugins/dataTypes/PIN/PIN.state';
import { generate as PhoneG } from '../client/src/plugins/dataTypes/Phone/Phone.generate';
import { defaultGenerationOptions as PhoneDGO } from '../client/src/plugins/dataTypes/Phone/Phone.state';
import { generate as PostalZipG } from '../client/src/plugins/dataTypes/PostalZip/PostalZip.generate';
import { defaultGenerationOptions as PostalZipDGO } from '../client/src/plugins/dataTypes/PostalZip/PostalZip.state';
import { generate as RegionG } from '../client/src/plugins/dataTypes/Region/Region.generate';
import { defaultGenerationOptions as RegionDGO } from '../client/src/plugins/dataTypes/Region/Region.state';
import { generate as RutG } from '../client/src/plugins/dataTypes/Rut/Rut.generate';
import { defaultGenerationOptions as RutDGO } from '../client/src/plugins/dataTypes/Rut/Rut.state';
import { generate as StreetAddressG } from '../client/src/plugins/dataTypes/StreetAddress/StreetAddress.generate';
import { defaultGenerationOptions as StreetAddressDGO } from '../client/src/plugins/dataTypes/StreetAddress/StreetAddress.state';
import { generate as TextFixedG } from '../client/src/plugins/dataTypes/TextFixed/TextFixed.generate';
import { defaultGenerationOptions as TextFixedDGO } from '../client/src/plugins/dataTypes/TextFixed/TextFixed.state';
import { generate as TextRandomG } from '../client/src/plugins/dataTypes/TextRandom/TextRandom.generate';
import { defaultGenerationOptions as TextRandomDGO } from '../client/src/plugins/dataTypes/TextRandom/TextRandom.state';
import { generate as TimeG } from '../client/src/plugins/dataTypes/Time/Time.generate';
import { defaultGenerationOptions as TimeDGO } from '../client/src/plugins/dataTypes/Time/Time.state';
import { generate as Track1G } from '../client/src/plugins/dataTypes/Track1/Track1.generate';
import { defaultGenerationOptions as Track1DGO } from '../client/src/plugins/dataTypes/Track1/Track1.state';
import { generate as Track2G } from '../client/src/plugins/dataTypes/Track2/Track2.generate';
import { defaultGenerationOptions as Track2DGO } from '../client/src/plugins/dataTypes/Track2/Track2.state';
import { generate as URLsG } from '../client/src/plugins/dataTypes/URLs/URLs.generate';
import { defaultGenerationOptions as URLsDGO } from '../client/src/plugins/dataTypes/URLs/URLs.state';
import { generate as WeightedListG } from '../client/src/plugins/dataTypes/WeightedList/WeightedList.generate';
import { defaultGenerationOptions as WeightedListDGO } from '../client/src/plugins/dataTypes/WeightedList/WeightedList.state';


export const dataTypeNodeData = {
	[DataType.Alphanumeric]: { generate: AlphanumericG, defaultGenerationOptions: AlphanumericDGO },
	[DataType.AutoIncrement]: { generate: AutoIncrementG, defaultGenerationOptions: AutoIncrementDGO },
	[DataType.Boolean]: { generate: BooleanG, defaultGenerationOptions: BooleanDGO },
	[DataType.CVV]: { generate: CVVG, defaultGenerationOptions: CVVDGO },
	[DataType.City]: { generate: CityG, defaultGenerationOptions: CityDGO },
	[DataType.Colour]: { generate: ColourG, defaultGenerationOptions: ColourDGO },
	[DataType.Company]: { generate: CompanyG, defaultGenerationOptions: CompanyDGO },
	[DataType.Computed]: { generate: ComputedG, defaultGenerationOptions: ComputedDGO },
	[DataType.Constant]: { generate: ConstantG, defaultGenerationOptions: ConstantDGO },
	[DataType.Country]: { generate: CountryG, defaultGenerationOptions: CountryDGO },
	[DataType.Currency]: { generate: CurrencyG, defaultGenerationOptions: CurrencyDGO },
	[DataType.Date]: { generate: DateG, defaultGenerationOptions: DateDGO },
	[DataType.Email]: { generate: EmailG, defaultGenerationOptions: EmailDGO },
	[DataType.GUID]: { generate: GUIDG, defaultGenerationOptions: GUIDDGO },
	[DataType.IBAN]: { generate: IBANG, defaultGenerationOptions: IBANDGO },
	[DataType.LatLng]: { generate: LatLngG, defaultGenerationOptions: LatLngDGO },
	[DataType.List]: { generate: ListG, defaultGenerationOptions: ListDGO },
	[DataType.Names]: { generate: NamesG, defaultGenerationOptions: NamesDGO },
	[DataType.NormalDistribution]: { generate: NormalDistributionG, defaultGenerationOptions: NormalDistributionDGO },
	[DataType.NumberRange]: { generate: NumberRangeG, defaultGenerationOptions: NumberRangeDGO },
	[DataType.PAN]: { generate: PANG, defaultGenerationOptions: PANDGO },
	[DataType.PIN]: { generate: PING, defaultGenerationOptions: PINDGO },
	[DataType.Phone]: { generate: PhoneG, defaultGenerationOptions: PhoneDGO },
	[DataType.PostalZip]: { generate: PostalZipG, defaultGenerationOptions: PostalZipDGO },
	[DataType.Region]: { generate: RegionG, defaultGenerationOptions: RegionDGO },
	[DataType.Rut]: { generate: RutG, defaultGenerationOptions: RutDGO },
	[DataType.StreetAddress]: { generate: StreetAddressG, defaultGenerationOptions: StreetAddressDGO },
	[DataType.TextFixed]: { generate: TextFixedG, defaultGenerationOptions: TextFixedDGO },
	[DataType.TextRandom]: { generate: TextRandomG, defaultGenerationOptions: TextRandomDGO },
	[DataType.Time]: { generate: TimeG, defaultGenerationOptions: TimeDGO },
	[DataType.Track1]: { generate: Track1G, defaultGenerationOptions: Track1DGO },
	[DataType.Track2]: { generate: Track2G, defaultGenerationOptions: Track2DGO },
	[DataType.URLs]: { generate: URLsG, defaultGenerationOptions: URLsDGO },
	[DataType.WeightedList]: { generate: WeightedListG, defaultGenerationOptions: WeightedListDGO }
};

import { generate as CSVG } from '../client/src/plugins/exportTypes/CSV/CSV.generate';
import { defaultGenerationOptions as CSVDGO } from '../client/src/plugins/exportTypes/CSV/CSV.state';
import { generate as CSharpG } from '../client/src/plugins/exportTypes/CSharp/CSharp.generate';
import { defaultGenerationOptions as CSharpDGO } from '../client/src/plugins/exportTypes/CSharp/CSharp.state';
import { generate as HTMLG } from '../client/src/plugins/exportTypes/HTML/HTML.generate';
import { defaultGenerationOptions as HTMLDGO } from '../client/src/plugins/exportTypes/HTML/HTML.state';
import { generate as JSONG } from '../client/src/plugins/exportTypes/JSON/JSON.generate';
import { defaultGenerationOptions as JSONDGO } from '../client/src/plugins/exportTypes/JSON/JSON.state';
import { generate as JavascriptG } from '../client/src/plugins/exportTypes/Javascript/Javascript.generate';
import { defaultGenerationOptions as JavascriptDGO } from '../client/src/plugins/exportTypes/Javascript/Javascript.state';
import { generate as LDIFG } from '../client/src/plugins/exportTypes/LDIF/LDIF.generate';
import { defaultGenerationOptions as LDIFDGO } from '../client/src/plugins/exportTypes/LDIF/LDIF.state';
import { generate as PHPG } from '../client/src/plugins/exportTypes/PHP/PHP.generate';
import { defaultGenerationOptions as PHPDGO } from '../client/src/plugins/exportTypes/PHP/PHP.state';
import { generate as PerlG } from '../client/src/plugins/exportTypes/Perl/Perl.generate';
import { defaultGenerationOptions as PerlDGO } from '../client/src/plugins/exportTypes/Perl/Perl.state';
import { generate as PythonG } from '../client/src/plugins/exportTypes/Python/Python.generate';
import { defaultGenerationOptions as PythonDGO } from '../client/src/plugins/exportTypes/Python/Python.state';
import { generate as RubyG } from '../client/src/plugins/exportTypes/Ruby/Ruby.generate';
import { defaultGenerationOptions as RubyDGO } from '../client/src/plugins/exportTypes/Ruby/Ruby.state';
import { generate as SQLG } from '../client/src/plugins/exportTypes/SQL/SQL.generate';
import { defaultGenerationOptions as SQLDGO } from '../client/src/plugins/exportTypes/SQL/SQL.state';
import { generate as TypescriptG } from '../client/src/plugins/exportTypes/Typescript/Typescript.generate';
import { defaultGenerationOptions as TypescriptDGO } from '../client/src/plugins/exportTypes/Typescript/Typescript.state';
import { generate as XMLG } from '../client/src/plugins/exportTypes/XML/XML.generate';
import { defaultGenerationOptions as XMLDGO } from '../client/src/plugins/exportTypes/XML/XML.state';


export const exportTypeNodeData = {
	[ExportType.CSV]: { generate: CSVG, defaultGenerationOptions: CSVDGO },
	[ExportType.CSharp]: { generate: CSharpG, defaultGenerationOptions: CSharpDGO },
	[ExportType.HTML]: { generate: HTMLG, defaultGenerationOptions: HTMLDGO },
	[ExportType.JSON]: { generate: JSONG, defaultGenerationOptions: JSONDGO },
	[ExportType.Javascript]: { generate: JavascriptG, defaultGenerationOptions: JavascriptDGO },
	[ExportType.LDIF]: { generate: LDIFG, defaultGenerationOptions: LDIFDGO },
	[ExportType.PHP]: { generate: PHPG, defaultGenerationOptions: PHPDGO },
	[ExportType.Perl]: { generate: PerlG, defaultGenerationOptions: PerlDGO },
	[ExportType.Python]: { generate: PythonG, defaultGenerationOptions: PythonDGO },
	[ExportType.Ruby]: { generate: RubyG, defaultGenerationOptions: RubyDGO },
	[ExportType.SQL]: { generate: SQLG, defaultGenerationOptions: SQLDGO },
	[ExportType.Typescript]: { generate: TypescriptG, defaultGenerationOptions: TypescriptDGO },
	[ExportType.XML]: { generate: XMLG, defaultGenerationOptions: XMLDGO }
};

