/**
 * This file is autogenerated. Do not edit!
 * ----------------------------------------
 **/

import { DataType } from '../client/_plugins';
import { generate as AlphanumericG, defaultGenerationOptions as AlphanumericDGO } from '../client/src/plugins/dataTypes/Alphanumeric/bundle';
import { generate as AutoIncrementG, defaultGenerationOptions as AutoIncrementDGO } from '../client/src/plugins/dataTypes/AutoIncrement/bundle';
import { generate as BooleanG, defaultGenerationOptions as BooleanDGO } from '../client/src/plugins/dataTypes/Boolean/bundle';
import { generate as CVVG, defaultGenerationOptions as CVVDGO } from '../client/src/plugins/dataTypes/CVV/bundle';
import { generate as CityG, defaultGenerationOptions as CityDGO } from '../client/src/plugins/dataTypes/City/bundle';
import { generate as ColourG, defaultGenerationOptions as ColourDGO } from '../client/src/plugins/dataTypes/Colour/bundle';
import { generate as CompanyG, defaultGenerationOptions as CompanyDGO } from '../client/src/plugins/dataTypes/Company/bundle';
import { generate as ComputedG, defaultGenerationOptions as ComputedDGO } from '../client/src/plugins/dataTypes/Computed/bundle';
import { generate as ConstantG, defaultGenerationOptions as ConstantDGO } from '../client/src/plugins/dataTypes/Constant/bundle';
import { generate as CountryG, defaultGenerationOptions as CountryDGO } from '../client/src/plugins/dataTypes/Country/bundle';
import { generate as CurrencyG, defaultGenerationOptions as CurrencyDGO } from '../client/src/plugins/dataTypes/Currency/bundle';
import { generate as DateG, defaultGenerationOptions as DateDGO } from '../client/src/plugins/dataTypes/Date/bundle';
import { generate as EmailG, defaultGenerationOptions as EmailDGO } from '../client/src/plugins/dataTypes/Email/bundle';
import { generate as GUIDG, defaultGenerationOptions as GUIDDGO } from '../client/src/plugins/dataTypes/GUID/bundle';
import { generate as IBANG, defaultGenerationOptions as IBANDGO } from '../client/src/plugins/dataTypes/IBAN/bundle';
import { generate as LatLngG, defaultGenerationOptions as LatLngDGO } from '../client/src/plugins/dataTypes/LatLng/bundle';
import { generate as ListG, defaultGenerationOptions as ListDGO } from '../client/src/plugins/dataTypes/List/bundle';
import { generate as NamesG, defaultGenerationOptions as NamesDGO } from '../client/src/plugins/dataTypes/Names/bundle';
import { generate as NormalDistributionG, defaultGenerationOptions as NormalDistributionDGO } from '../client/src/plugins/dataTypes/NormalDistribution/bundle';
import { generate as NumberRangeG, defaultGenerationOptions as NumberRangeDGO } from '../client/src/plugins/dataTypes/NumberRange/bundle';
import { generate as PANG, defaultGenerationOptions as PANDGO } from '../client/src/plugins/dataTypes/PAN/bundle';
import { generate as PING, defaultGenerationOptions as PINDGO } from '../client/src/plugins/dataTypes/PIN/bundle';
import { generate as PhoneG, defaultGenerationOptions as PhoneDGO } from '../client/src/plugins/dataTypes/Phone/bundle';
import { generate as PostalZipG, defaultGenerationOptions as PostalZipDGO } from '../client/src/plugins/dataTypes/PostalZip/bundle';
import { generate as RegionG, defaultGenerationOptions as RegionDGO } from '../client/src/plugins/dataTypes/Region/bundle';
import { generate as RutG, defaultGenerationOptions as RutDGO } from '../client/src/plugins/dataTypes/Rut/bundle';
import { generate as StreetAddressG, defaultGenerationOptions as StreetAddressDGO } from '../client/src/plugins/dataTypes/StreetAddress/bundle';
import { generate as TextFixedG, defaultGenerationOptions as TextFixedDGO } from '../client/src/plugins/dataTypes/TextFixed/bundle';
import { generate as TextRandomG, defaultGenerationOptions as TextRandomDGO } from '../client/src/plugins/dataTypes/TextRandom/bundle';
import { generate as TimeG, defaultGenerationOptions as TimeDGO } from '../client/src/plugins/dataTypes/Time/bundle';
import { generate as Track1G, defaultGenerationOptions as Track1DGO } from '../client/src/plugins/dataTypes/Track1/bundle';
import { generate as Track2G, defaultGenerationOptions as Track2DGO } from '../client/src/plugins/dataTypes/Track2/bundle';
import { generate as URLsG, defaultGenerationOptions as URLsDGO } from '../client/src/plugins/dataTypes/URLs/bundle';
import { generate as WeightedListG, defaultGenerationOptions as WeightedListDGO } from '../client/src/plugins/dataTypes/WeightedList/bundle';


export const dataTypeGenerateMethods = {
	[DataType.Alphanumeric]: { generate: AlphanumericG, defaultGenerationOptions: AlphanumericDGO },
	[DataType.AutoIncrement]: { generate: AutoIncrementG, defaultGenerationOptions: AutoIncrementDGO },
	[DataType.Boolean]: { generate: BooleanG, defaultGenerationOptions: BooleanDGO },
	[DataType.CVV]: { generate: CVVG, defaultGenerationOptions: CVVDGO },
	[DataType.City]: { generate: CityG, defaultGenerationOptions: CityDGO },
	[DataType.Colour]: { generate: ColourG, defaultGenerationOptions: ColourDGO },
	[DataType.Company]: { generate: CompanyG, defaultGenerationOptions: CompanyDGO },
	[DataType.Computed]: { generate: ComputedG, defaultGenerationOptions: ComputedDGO },
	[DataType.Constant]: { generate: ConstantG, defaultGenerationOptions: ConstantDGO },
	[DataType.Country]: { generate: CountryG, defaultGenerationOptions: CountryDGO },
	[DataType.Currency]: { generate: CurrencyG, defaultGenerationOptions: CurrencyDGO },
	[DataType.Date]: { generate: DateG, defaultGenerationOptions: DateDGO },
	[DataType.Email]: { generate: EmailG, defaultGenerationOptions: EmailDGO },
	[DataType.GUID]: { generate: GUIDG, defaultGenerationOptions: GUIDDGO },
	[DataType.IBAN]: { generate: IBANG, defaultGenerationOptions: IBANDGO },
	[DataType.LatLng]: { generate: LatLngG, defaultGenerationOptions: LatLngDGO },
	[DataType.List]: { generate: ListG, defaultGenerationOptions: ListDGO },
	[DataType.Names]: { generate: NamesG, defaultGenerationOptions: NamesDGO },
	[DataType.NormalDistribution]: { generate: NormalDistributionG, defaultGenerationOptions: NormalDistributionDGO },
	[DataType.NumberRange]: { generate: NumberRangeG, defaultGenerationOptions: NumberRangeDGO },
	[DataType.PAN]: { generate: PANG, defaultGenerationOptions: PANDGO },
	[DataType.PIN]: { generate: PING, defaultGenerationOptions: PINDGO },
	[DataType.Phone]: { generate: PhoneG, defaultGenerationOptions: PhoneDGO },
	[DataType.PostalZip]: { generate: PostalZipG, defaultGenerationOptions: PostalZipDGO },
	[DataType.Region]: { generate: RegionG, defaultGenerationOptions: RegionDGO },
	[DataType.Rut]: { generate: RutG, defaultGenerationOptions: RutDGO },
	[DataType.StreetAddress]: { generate: StreetAddressG, defaultGenerationOptions: StreetAddressDGO },
	[DataType.TextFixed]: { generate: TextFixedG, defaultGenerationOptions: TextFixedDGO },
	[DataType.TextRandom]: { generate: TextRandomG, defaultGenerationOptions: TextRandomDGO },
	[DataType.Time]: { generate: TimeG, defaultGenerationOptions: TimeDGO },
	[DataType.Track1]: { generate: Track1G, defaultGenerationOptions: Track1DGO },
	[DataType.Track2]: { generate: Track2G, defaultGenerationOptions: Track2DGO },
	[DataType.URLs]: { generate: URLsG, defaultGenerationOptions: URLsDGO },
	[DataType.WeightedList]: { generate: WeightedListG, defaultGenerationOptions: WeightedListDGO }
};

