const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const clientConfig = require('@generatedata/config/clientConfig');

const locales = clientConfig.default.appSettings.GD_LOCALES;

const distFolder = path.join(__dirname, '/dist');
if (!fs.existsSync(distFolder)) {
  fs.mkdirSync(distFolder);
}

// move the logic to gather up all localization files from into a `tools` package. It'll be used in CLI too. For 5.0.0
// we can probably punt on this though.
module.exports = function (grunt) {
  const dataTypesFolder = 'dataTypes';
  const exportTypesFolder = 'exportTypes';
  const countriesFolder = 'countries';

  const generateI18nBundles = () => {
    const fileHashMap = locales.reduce((acc, locale) => {
      const coreLocaleStrings = JSON.parse(fs.readFileSync(require.resolve(`@generatedata/i18n/${locale}`), 'utf8'));
      const dtImports = getPluginLocaleFiles(grunt, locale, dataTypesFolder);
      const etImports = getPluginLocaleFiles(grunt, locale, exportTypesFolder);
      const countryImports = getPluginLocaleFiles(grunt, locale, countriesFolder);

      acc = {
        ...acc,
        ...generateLocaleFileTemplate(locale, coreLocaleStrings, dtImports, etImports, countryImports)
      };
      return acc;
    }, {});

    // generate the i18n hashmap file. This is imported by the source code to know what files to load
    generateI18nHashMap(fileHashMap);
  };

  const generateI18nHashMap = (content) => {
    const filename = './_localeFileMap.ts';
    const tsContent = `import type { GDLocaleMap } from '@generatedata/config';

export const localeFileMap: GDLocaleMap = ${JSON.stringify(content, null, '\t')};`;
    fs.writeFileSync(filename, tsContent);
  };

  const getPluginLocaleFiles = (grunt, locale, pluginTypeFolder) => {
    const fullPluginFolder = path.resolve(__dirname, `./node_modules/@generatedata/plugins/dist/${pluginTypeFolder}`);
    const plugins = fs.readdirSync(fullPluginFolder);
    const imports = {};
    plugins.forEach((folder) => {
      const localeFile = `${fullPluginFolder}/${folder}/i18n/${locale}.json`;
      if (fs.existsSync(localeFile)) {
        try {
          imports[folder] = JSON.parse(fs.readFileSync(localeFile, 'utf8'));
        } catch (e) {
          grunt.fail.fatal('problem parsing i18n file: ' + localeFile);
        }
      }
    });
    return imports;
  };

  const generateLocaleFileTemplate = (locale, coreLocaleStrings, dtImports, etImports, countryImports) => {
    const template = `// DO NOT EDIT. This file is generated by a Grunt task.
// ----------------------------------------------------

(function() { 
const i18n = {
	core: ${JSON.stringify(coreLocaleStrings)},
	dataTypes: ${JSON.stringify(dtImports)},
	exportTypes: ${JSON.stringify(etImports)},
	countries: ${JSON.stringify(countryImports)}
};

// load the locale info via an exposed global
window.gd.localeLoaded(i18n);
})();`;

    const filename = `./dist/${locale}.js`;
    fs.writeFileSync(filename, template);

    const hash = getFilenameHash(filename);
    const hashedFilename = `${locale}-${hash}.js`;
    fs.renameSync(filename, `./dist/${hashedFilename}`);

    return {
      [locale]: hashedFilename
    };
  };

  grunt.initConfig({
    cssmin: {
      options: {
        mergeIntoShorthands: false,
        roundingPrecision: -1
      },
      target: {
        files: {
          'dist/styles.css': [
            'src/resources/global.css',
            'src/resources/codemirror.css',
            'src/resources/ambience.css',
            'src/resources/bespin.css',
            'src/resources/cobalt.css',
            'src/resources/darcula.css',
            'src/resources/lucario.css'
          ]
        }
      }
    },
    copy: {
      main: {
        files: [
          {
            expand: true,
            cwd: 'src/images',
            src: ['*'],
            dest: 'dist/images/'
          }
        ]
      },
      // TODO should minify these too
      codeMirrorModes: {
        files: [
          {
            expand: true,
            cwd: './node_modules/codemirror/mode',
            src: ['**/*'],
            dest: 'dist/codeMirrorModes/'
          }
        ]
      },
      pluginWorkers: {
        files: [
          {
            expand: true,
            cwd: './node_modules/@generatedata/plugins/dist/workers',
            src: ['**/*'],
            dest: 'dist/workers/'
          },
          {
            expand: true,
            cwd: './node_modules/@generatedata/utils/dist/workers',
            src: ['**/*'],
            dest: 'dist/workers/'
          }
        ]
      }
    },
    watch: {},
    clean: {
      dist: ['dist']
    }
  });

  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-shell');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-md5');

  grunt.registerTask('default', ['cssmin', 'copy', 'generateI18nBundles']);
  grunt.registerTask('dev', ['cssmin', 'copy', 'generateI18nBundles', 'watch']);
  grunt.registerTask('generateI18nBundles', generateI18nBundles);
};
