import { ApolloProvider } from '@apollo/client/react';
import type { GDLocale } from '@generatedata/config';
import type { CountryNames, DataTypeFolder, ExportTypeFolder } from '@generatedata/plugins';
import { setLocale } from '@generatedata/utils/lang';
import { configureStore } from '@reduxjs/toolkit';
import { render } from '@testing-library/react';
import { createMemoryHistory } from 'history';
import React from 'react';
import { Provider } from 'react-redux';
import { Router } from 'react-router-dom';
import { combineReducers } from 'redux';
import { apolloClient } from '~core/apolloClient';
import accountReducer, { getInitialState as getInitialAccountState } from '~store/account/account.reducer';
import generatorReducer, { getInitialState } from '~store/generator/generator.reducer';
import { setLocaleFileLoaded } from '~store/main/main.actions';
import mainReducer, { getInitialState as getMainInitialState } from '~store/main/main.reducer';
import packetsReducer, { getInitialState as getInitialPacketState } from '~store/packets/packets.reducer';

// @ts-ignore - TODO
import jsonI18n from '@generatedata/plugins/dist/exportTypes/JSON/i18n/en.json';

// Import the full i18n bundles generated by @generatedata/i18n package
import enI18n from '@generatedata/i18n/locales/en';

/**
 * Full i18n bundle structure containing all localized strings for the application.
 */
export type I18nBundle = {
  core: Record<string, string>;
  dataTypes: Record<DataTypeFolder, Record<string, string>>;
  exportTypes: Record<ExportTypeFolder, Record<string, string>>;
  countries: Record<CountryNames, Record<string, string>>;
};

/**
 * Loads the full i18n bundle for a given locale.
 * This provides access to all localized strings including core, dataTypes, exportTypes, and countries.
 *
 * @param locale - The locale to load (defaults to 'en')
 * @returns The full i18n bundle containing core, dataTypes, exportTypes, and countries strings
 *
 * @example
 * // Get the full English i18n bundle
 * const i18n = getTestI18n();
 *
 * // Access core strings
 * const coreStrings = i18n.core;
 *
 * // Access a specific data type's strings
 * const namesI18n = i18n.dataTypes.Names;
 */
export const getTestI18n = (locale: GDLocale = 'en'): I18nBundle => {
  // Currently only English is supported for tests; add other locales as needed
  if (locale !== 'en') {
    throw new Error(`Locale "${locale}" is not currently supported in tests. Add the import to testHelpers.tsx.`);
  }
  return enI18n as I18nBundle;
};

/**
 * Gets the i18n strings for a specific Data Type plugin.
 *
 * @param dataType - The data type folder name (e.g., 'Names', 'Email', 'Phone')
 * @param locale - The locale to load (defaults to 'en')
 * @returns The i18n strings for the specified data type
 *
 * @example
 * const namesI18n = getDataTypeI18n('Names');
 * const emailI18n = getDataTypeI18n('Email');
 */
export const getDataTypeI18n = (dataType: DataTypeFolder, locale: GDLocale = 'en'): Record<string, string> => {
  return getTestI18n(locale).dataTypes[dataType];
};

/**
 * Gets the i18n strings for a specific Export Type plugin.
 *
 * @param exportType - The export type folder name (e.g., 'JSON', 'CSV', 'SQL')
 * @param locale - The locale to load (defaults to 'en')
 * @returns The i18n strings for the specified export type
 *
 * @example
 * const jsonI18n = getExportTypeI18n('JSON');
 * const sqlI18n = getExportTypeI18n('SQL');
 */
export const getExportTypeI18n = (exportType: ExportTypeFolder, locale: GDLocale = 'en'): Record<string, string> => {
  return getTestI18n(locale).exportTypes[exportType];
};

/**
 * Gets the i18n strings for a specific Country plugin.
 *
 * @param country - The country name (e.g., 'Canada', 'US', 'UK')
 * @param locale - The locale to load (defaults to 'en')
 * @returns The i18n strings for the specified country
 *
 * @example
 * const canadaI18n = getCountryI18n('Canada');
 * const usI18n = getCountryI18n('US');
 */
export const getCountryI18n = (country: CountryNames, locale: GDLocale = 'en'): Record<string, string> => {
  return getTestI18n(locale).countries[country];
};

export const rootReducer = combineReducers({
  generator: generatorReducer,
  main: mainReducer,
  packets: packetsReducer,
  account: accountReducer
});

export const renderWithStoreAndRouter = (component: any) => {
  const initialState = getTestState();
  const store = configureStore({
    reducer: rootReducer,
    preloadedState: initialState
    // compose(applyMiddleware(thunk, actionsInterceptor
  });
  const route = '/';
  const history = createMemoryHistory({ initialEntries: [route] });

  setLocale('en', {
    core: enI18n.core,
    dataTypes: {},
    exportTypes: {
      JSON: jsonI18n
    },
    countries: {}
  });
  store.dispatch(setLocaleFileLoaded('en'));

  return {
    ...render(
      <ApolloProvider client={apolloClient}>
        <Provider store={store}>
          <Router navigator={history} location={history.location} navigationType={history.action}>
            {component}
          </Router>
        </Provider>
      </ApolloProvider>
    ),
    history
  };
};

export const getTestState = () => ({
  generator: getInitialState(),
  main: getMainInitialState(),
  packets: { ...getInitialPacketState() },
  account: { ...getInitialAccountState() }
});
