import type { GDClientConfig } from '../typings';

const config: GDClientConfig = {
  appSettings: {
    // this setting controls the overall type of the installation. It's used on initial installation only. The options are:
    //    login - allows anonymous access via the browser, but unless the user has logged in they can't save their data sets
    //            or generate more rows than GD_MAX_DEMO_MODE_ROWS at a time
    //    single - there's only ever a single account and that user is logged in by default
    //    open - anyone that has access to the URL can use the application anonymously or create an account
    //    closed - no-one can access it without logging in first
    GD_APP_TYPE: 'login',

    // this allows easy extension for the prod site. On the prod site, the homepage is a splash info page to the tool. For
    // other distributions, that isn't necessary
    GD_GENERATOR_PATH: '/',

    // the default locale for people visiting the app
    GD_DEFAULT_LOCALE: 'en',

    // the default Export Type that's show in the preview panel. The accepted values are any of the folder names of the
    // available Export Types. See the packages/plugins package for that.
    GD_DEFAULT_EXPORT_TYPE: 'JSON',

    // this controls what locales show up in the UI. If you only enter 1, the icon to switch locales won't appear. If you
    // want to add other locales, awesome! PRs welcome :)
    GD_LOCALES: ['ar', 'de', 'en', 'es', 'fr', 'hi', 'ja', 'nl', 'pt', 'ru', 'ta', 'zh'],

    // the default value for the number of rows to generate
    GD_DEFAULT_NUM_ROWS: 100,

    // for `login` appType, this controls how many rows can be generated by anonymous (non-logged in) users
    GD_MAX_DEMO_MODE_ROWS: 1000,

    // any time a user saves a dataset, that change is stored in the database to allow the user to backtrack and see
    // earlier versions of the dataset. This governs the max number of history items
    GD_MAX_DATASET_HISTORY_SIZE: 200,

    // this omits specific Data Types from the application. It omits them from appearing in the UI.
    GD_DATA_TYPE_BLACKLIST: ['BitcoinAddress', 'OrganizationNumber', 'PersonalNumber', 'SIRET'],

    // this omits specific Export Types from the application. It omits them from appearing in the UI.
    GD_EXPORT_TYPE_BLACKLIST: [],

    // omits specific Country plugins from appearing in the application; comma-delimited (no spaces!)
    GD_COUNTRY_BLACKLIST: [],

    // used for extension purposes only. TODO
    GD_IMPORT_FILES: []
  },

  auth: {
    // controls the lifespan of the JWT. Suggest you leave this setting alone
    GD_JWT_LIFESPAN_MINS: 15,

    // if you want to enable the "Login with Google" feature, this contains the google auth client ID
    GD_GOOGLE_AUTH_CLIENT_ID: ''
  },

  api: {
    // the server port for the graphql server
    GD_API_SERVER_PORT: 3001
  },

  webServer: {
    // controls the URL you'll load up in the browser to see the app
    GD_WEB_DOMAIN: 'localhost',

    // the webserver port
    GD_WEB_SERVER_PORT: 9000,

    // https vs http. Runnign `https` locally is always fussy as heck, so leave as false unless strictly necessary
    GD_WEB_USE_HTTPS: false
  }
};

export default config;
