export type AppType = 'login' | 'open' | 'closed' | 'prod';

export type GDLocale = 'ar' | 'de' | 'en' | 'es' | 'es' | 'fr' | 'hi' | 'ja' | 'nl' | 'pt' | 'ru' | 'ta' | 'zh';

export type GenerateDataConfig = {
  database: {
    GD_MYSQL_ROOT_USER: string;
    GD_MYSQL_ROOT_PASSWORD: string;
    GD_DB_NAME: string;
    GD_DB_PORT: number;
  };
  api: {
    GD_API_SERVER_PORT: number;
  };
  webServer: {
    GD_WEB_DOMAIN: string;
    GD_WEB_SERVER_PORT: number;
    GD_WEB_USE_HTTPS: boolean;
  };
  // Default admin account. You can either set these values before installing the app, or customize the values via the UI
  // afterwards. After creating the app these values aren't used.
  adminAccount: {
    GD_DEFAULT_ADMIN_FIRST_NAME: string;
    GD_DEFAULT_ADMIN_LAST_NAME: string;
    GD_DEFAULT_ADMIN_EMAIL_SENDER_NAME: string;
    GD_DEFAULT_ADMIN_EMAIL: string;
    GD_DEFAULT_ADMIN_PASSWORD: string;
  };
  auth: {
    // (Required) JWT secret. This is used for the JWT generation code. It should be changed to any string you like
    GD_JWT_SECRET: string;
    GD_JWT_LIFESPAN_MINS: number;
    GD_JWT_REFRESH_TOKEN_SECRET: string;
    GD_JWT_REFRESH_TOKEN_LIFESPAN_MINS: number;

    // (optional) Sign-in with Google - oath2
    GD_GOOGLE_AUTH_CLIENT_ID: string;
    GD_GOOGLE_AUTH_CLIENT_SECRET: string;
  };
  // Email OAUTH info
  email: {
    GD_EMAIL_OAUTH_SERVICE_CLIENT_ID: '';
    GD_EMAIL_OAUTH_PRIVATE_KEY: '';
  };
  appSettings: {
    // this setting controls the overall type of the installation. The options are:
    //    login - allows anonymous access but without logging in they can't save their data sets or generate more than
    //            appSettings.GD_MAX_DEMO_MODE_ROWS at a time.
    //    single - there's only ever a single account and that user is logged in by default
    //    open - anyone that has access to the URL can use the application anonymously or create an account
    //    closed - no-one can access it without logging in first
    GD_APP_TYPE: AppType;

    // this allows easy extension for the prod site. On the prod site, the homepage is a splash info page to the tool. For
    // other distributions, that isn't necessary
    GD_GENERATOR_PATH: string;

    // the default locale
    GD_DEFAULT_LOCALE: GDLocale;

    // the default Export Type to show in the preview panel
    GD_DEFAULT_EXPORT_TYPE: 'JSON';

    // controls what locales show up in the UI. If you only enter 1, the icon to switch locales won't appear. If you
    // want to add other locales, awesome! PRs welcome :)
    GD_LOCALES: GDLocale[];

    // the default value for the number of rows to generate
    GD_DEFAULT_NUM_ROWS: number;

    // for `login` appType, this controls how many rows can be generated by anonymous (non-logged in) users
    GD_MAX_DEMO_MODE_ROWS: number;

    // any time a user saves a dataset, that change is stored in the database to allow the user to backtrack and see
    // earlier versions of the dataset. This governs the max number of history items
    GD_MAX_DATASET_HISTORY_SIZE: number;

    // this omits specific Data Types from the application. Comma-delimited (no spaces!). It omits them from appearing in
    // the UI, but it also prevents them from being built as well. So incomplete Data Types won't throw an error and
    // cause the build to fail
    GD_DATA_TYPE_BLACKLIST: string[];

    // omits specific Export Types from the application; comma-delimited (no spaces!)
    GD_EXPORT_TYPE_BLACKLIST: string[];

    // omits specific Country plugins from appearing in the application; comma-delimited (no spaces!)
    GD_COUNTRY_BLACKLIST: string[];

    // used for extension purposes
    GD_IMPORT_FILES: string[];

    // unavailable just now. This enables/disables the REST API to allow users to generate data via a REST interface
    GD_REST_API_ENABLED: boolean;
  };
};
