FROM node:12-alpine AS alpine

ENV HOME=/home/app/generatedata

WORKDIR $HOME/server
COPY package.json yarn.lock $HOME/server/
RUN yarn install --network-timeout 100000 && npm install -g grunt-cli
COPY . $HOME/server/

CMD ["yarn", "start"]
