<?php

class Country_Canada extends CountryPlugin {
	protected $countryName = "Canada";
	protected $countrySlug = "canada";
	protected $regionNames = "Provinces";
	protected $zipFormat = "LXL XLx";

	static function install() {
		return array(true, "");
	}
}

/*
('nova_scotia', 'Municipal District'),
	('nova_scotia', 'Town of Yarmouth'),
	('nova_scotia', 'Wolfville'),
	('nova_scotia', 'Pugwash'),
	('nova_scotia', 'Pictou'),
	('nova_scotia', 'New Glasgow'),
	('nova_scotia', 'Halifax'),
	('nova_scotia', 'Guysborough'),
	('nova_scotia', 'Cumberland County'),
	('nova_scotia', 'Cape Breton Island'),
	('nova_scotia', 'Berwick'),
	('nova_scotia', 'Baddeck'),
	('nova_scotia', 'Argyle'),
	('nova_scotia', 'Annapolis Royal'),
	('nova_scotia', 'Annapolis County'),
	('northwest_territories', 'Yellowknife'),
	('northwest_territories', 'Wrigley'),
	('northwest_territories', 'Wha Ti'),
	('northwest_territories', 'Wekweti'),
	('northwest_territories', 'Tulita'),
	('northwest_territories', 'Tuktoyaktuk'),
	('northwest_territories', 'Tsiigehtchic'),
	('northwest_territories', 'Sachs Harbour'),
	('northwest_territories', 'Rae Lakes'),
	('northwest_territories', 'Rae-Edzo'),
	('northwest_territories', 'Paulatuk'),
	('northwest_territories', 'Norman Wells'),
	('northwest_territories', 'Lutsel K''e'),
	('northwest_territories', 'Kakisa'),
	('northwest_territories', 'Inuvik'),
	('northwest_territories', 'Holman'),
	('northwest_territories', 'Hay River'),
	('northwest_territories', 'Fort Smith'),
	('northwest_territories', 'Fort Simpson'),
	('northwest_territories', 'Fort Resolution'),
	('northwest_territories', 'Fort Providence'),
	('northwest_territories', 'Fort McPherson'),
	('northwest_territories', 'Fort Laird'),
	('northwest_territories', 'Fort Good Hope'),
	('northwest_territories', 'Enterprise'),
	('northwest_territories', 'Deline'),
	('northwest_territories', 'Coleville Lake'),
	('northwest_territories', 'Aklavik'),
	('newfoundland', 'St. John''s'),
	('newfoundland', 'Springdale'),
	('newfoundland', 'Spaniard''s Bay'),
	('newfoundland', 'Rigolet'),
	('newfoundland', 'Paradise'),
	('newfoundland', 'Mount Pearl'),
	('newfoundland', 'McCallum'),
	('newfoundland', 'Marystown'),
	('newfoundland', 'Harbour Grace'),
	('newfoundland', 'Glovertown'),
	('newfoundland', 'Gander'),
	('newfoundland', 'Fogo'),
	('newfoundland', 'Fortune'),
	('newfoundland', 'Carbonear'),
	('newfoundland', 'Burin'),
	('newfoundland', 'Bonavista'),
	('newfoundland', 'Bay Roberts'),
	('new_brunswick', Tracadie-Shelia'),
	('new_brunswick', 'Shédiac'),
	('new_brunswick', 'Shippagan'),
	('new_brunswick', 'Saint-Léonard'),
	('new_brunswick', 'Saint John'),
	('new_brunswick', 'Saint André'),
	('new_brunswick', 'Rothesay'),
	('new_brunswick', 'Rexton'),
	('new_brunswick', 'Quispamsis'),
	('new_brunswick', 'Oromocto'),
	('new_brunswick', 'New Maryland'),
	('new_brunswick', 'Moncton'),
	('new_brunswick', 'Miramichi'),
	('new_brunswick', 'Grand Falls'),
	('new_brunswick', 'Fredericton'),
	('new_brunswick', 'Edmundston'),
	('new_brunswick', 'Dieppe'),
	('new_brunswick', 'Clare'),
	('new_brunswick', 'Cap-Pelé'),
	('new_brunswick', 'Carlton'),
	('manitoba', 'Winnipeg'),
	('manitoba', 'Stonewall'),
	('manitoba', 'Minitonas'),
	('manitoba', 'Lourdes'),
	('manitoba', 'Flin Flon'),
	('manitoba', 'Daly'),
	('manitoba', 'Brandon'),
	('manitoba', 'Beausejour'),

 */