// This file is autogenerated. Do not edit!
export type DataType = 'AutoIncrement';
export const dataTypes = [
	{ name: 'AutoIncrement', folder: 'AutoIncrement', folderPath: '...', fieldGroup: 'numeric', fieldGroupOrder: 20, processOrder: 0 }
];

export type ExportType = 'CSV' | 'JSON' | 'SQL';
export const exportTypes = [
	{ name: 'JSON', folder: 'JSON' }
];
