export default {
  '0b68cd7a': [() => import(/* webpackChunkName: '0b68cd7a' */ "@site/docs/userdoc/about/purpose.md"), "@site/docs/userdoc/about/purpose.md", require.resolveWeak("@site/docs/userdoc/about/purpose.md")],
  '13c81200': [() => import(/* webpackChunkName: '13c81200' */ "@site/docs/userdoc/about/website.md"), "@site/docs/userdoc/about/website.md", require.resolveWeak("@site/docs/userdoc/about/website.md")],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  '5cb9be24': [() => import(/* webpackChunkName: '5cb9be24' */ "@site/docs/userdoc/installation/intro.md"), "@site/docs/userdoc/installation/intro.md", require.resolveWeak("@site/docs/userdoc/installation/intro.md")],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  '63daaf52': [() => import(/* webpackChunkName: '63daaf52' */ "@site/docs/userdoc/about/history.md"), "@site/docs/userdoc/about/history.md", require.resolveWeak("@site/docs/userdoc/about/history.md")],
  '661e67c3': [() => import(/* webpackChunkName: '661e67c3' */ "@site/docs/developerdoc/index.md"), "@site/docs/developerdoc/index.md", require.resolveWeak("@site/docs/developerdoc/index.md")],
  '6f73fa8e': [() => import(/* webpackChunkName: '6f73fa8e' */ "~blog/default/generatedata-blog-archive-41e.json"), "~blog/default/generatedata-blog-archive-41e.json", require.resolveWeak("~blog/default/generatedata-blog-archive-41e.json")],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  '9dd6ade5': [() => import(/* webpackChunkName: '9dd6ade5' */ "@site/docs/userdoc/about/version-comparison.md"), "@site/docs/userdoc/about/version-comparison.md", require.resolveWeak("@site/docs/userdoc/about/version-comparison.md")],
  '9e4087bc': [() => import(/* webpackChunkName: '9e4087bc' */ "@theme/BlogArchivePage"), "@theme/BlogArchivePage", require.resolveWeak("@theme/BlogArchivePage")],
  'b26b9b14': [() => import(/* webpackChunkName: 'b26b9b14' */ "@site/src/pages/index---old.js"), "@site/src/pages/index---old.js", require.resolveWeak("@site/src/pages/index---old.js")],
  'eec77540': [() => import(/* webpackChunkName: 'eec77540' */ "@site/docs/userdoc/welcome.md"), "@site/docs/userdoc/welcome.md", require.resolveWeak("@site/docs/userdoc/welcome.md")],
  'fed02bc4': [() => import(/* webpackChunkName: 'fed02bc4' */ "@site/docs/userdoc/v3.md"), "@site/docs/userdoc/v3.md", require.resolveWeak("@site/docs/userdoc/v3.md")],};
