import fs, { readFileSync } from 'fs';
import path from 'path';
import clientConfig from '@generatedata/config/clientConfig';
import { GDLocale } from '@generatedata/config';
import { createHash } from 'crypto';

// strips out any keys ending with `:comment` - these are used for translator context only
const stripCommentKeys = (obj: Record<string, unknown>): Record<string, unknown> => {
  return Object.fromEntries(Object.entries(obj).filter(([key]) => !key.endsWith(':comment')));
};

const LOCALES = clientConfig.appSettings.GD_LOCALES;
const DATA_TYPES_FOLDER = path.resolve(__dirname, '../node_modules/@generatedata/plugins/dist/dataTypes');
const EXPORT_TYPES_FOLDER = path.resolve(__dirname, '../node_modules/@generatedata/plugins/dist/exportTypes');
const COUNTRIES_FOLDER = path.resolve(__dirname, '../node_modules/@generatedata/plugins/dist/countries');
const DIST_FOLDER = path.resolve(__dirname, '../dist');
const I18N_CORE_FOLDER = path.resolve(__dirname, '../node_modules/@generatedata/i18n-core');

const generateI18nBundles = () => {
  const fileHashMap = LOCALES.reduce((acc, locale) => {
    const coreLocaleStrings = stripCommentKeys(
      JSON.parse(fs.readFileSync(path.join(I18N_CORE_FOLDER, 'locales', `${locale}.json`), 'utf8'))
    );
    const dtImports = getPluginLocaleFiles(locale, DATA_TYPES_FOLDER);
    const etImports = getPluginLocaleFiles(locale, EXPORT_TYPES_FOLDER);
    const countryImports = getPluginLocaleFiles(locale, COUNTRIES_FOLDER);

    acc = {
      ...acc,
      ...generateLocaleFileTemplate(locale, coreLocaleStrings, dtImports, etImports, countryImports)
    };
    return acc;
  }, {});

  // generate the i18n hashmap file. This is imported by the client app to know what minified files to actually load. That package
  // handles copying the build artifacts from this package to its own
  generateI18nHashMap(fileHashMap);
};

const generateI18nHashMap = (content: object) => {
  if (!fs.existsSync(DIST_FOLDER)) {
    fs.mkdirSync(DIST_FOLDER, { recursive: true });
  }

  const filename = `${DIST_FOLDER}/localeFileMap.ts`;
  const tsContent = `import type { GDLocaleMap } from '@generatedata/config';

export const localeFileMap: GDLocaleMap = ${JSON.stringify(content, null, '\t')};`;
  fs.writeFileSync(filename, tsContent);
};

const getPluginLocaleFiles = (locale: GDLocale, pluginTypeFolder: string) => {
  const plugins = fs.readdirSync(pluginTypeFolder);
  const imports: {
    [plugin: string]: { [key: string]: string };
  } = {};

  plugins.forEach((folder) => {
    const localeFile = `${pluginTypeFolder}/${folder}/i18n/${locale}.json`;
    if (fs.existsSync(localeFile)) {
      try {
        imports[folder] = stripCommentKeys(JSON.parse(fs.readFileSync(localeFile, 'utf8'))) as { [key: string]: string };
      } catch (e) {
        console.error('problem parsing i18n file: ' + localeFile);
        process.exit(1);
      }
    }
  });
  return imports;
};

const generateLocaleFileTemplate = (
  locale: GDLocale,
  coreLocaleStrings: object,
  dtImports: object,
  etImports: object,
  countryImports: object
) => {
  const i18nData = {
    core: coreLocaleStrings,
    dataTypes: dtImports,
    exportTypes: etImports,
    countries: countryImports
  };

  // Generate the IIFE version for browser usage
  const template = `// DO NOT EDIT. This file is generated by the @generatedata/i18n package
// ----------------------------------------------------

(function() {
const i18n = {
	core: ${JSON.stringify(coreLocaleStrings)},
	dataTypes: ${JSON.stringify(dtImports)},
	exportTypes: ${JSON.stringify(etImports)},
	countries: ${JSON.stringify(countryImports)}
};

// load the locale info via an exposed global
window.gd.localeLoaded(i18n);
})();`;

  if (!fs.existsSync(DIST_FOLDER)) {
    fs.mkdirSync(DIST_FOLDER, { recursive: true });
  }

  const filename = `${DIST_FOLDER}/${locale}.js`;
  fs.writeFileSync(filename, template);

  const hash = getFileHash(filename);
  const hashedFilename = `${locale}-${hash}.js`;
  fs.renameSync(filename, `${DIST_FOLDER}/${hashedFilename}`);

  // Also generate a simple JSON file for use in tests and other Node.js contexts
  const jsonFilename = `${DIST_FOLDER}/${locale}.json`;
  fs.writeFileSync(jsonFilename, JSON.stringify(i18nData, null, 2));

  return {
    [locale]: hashedFilename
  };
};

// returns an 8 char version of the filename hash, used for cache-busting
const getFileHash = (filePath: string, algorithm = 'sha256'): string => {
  const fileBuffer = readFileSync(filePath);
  return createHash(algorithm).update(new Uint8Array(fileBuffer)).digest('hex').slice(0, 8);
};

generateI18nBundles();
